### PR TITLE
Binary to edit a user's password

### PR DESCRIPTION
**Pull request by marceloschmidt**
I'm not sure if this is the best bash script it can be, but it works for me.
This script changes a user password.
We still need to restart the server for changes to be taken into account.

### CODE REVIEW

**Comment by Josef-Friedrich** [comment]
related to #357

**Comment by Influencer** [comment]
Just a suggestion, sed will do all the work in a single line. Try this out:

Remove lines 9-13(the sed_string function), remove 31 and replace line 32 from
`sed -i "s/${SED_STRING}" $DATABASE`
to
` sed -i.bak "s%^$USER.*%$ENTRY%g" $DATABASE `

That should search the database for $user and replace the line with the new $ENTRY. I added the .bak in case the user made a mistake and needed to rollback the change.

The only issue I could think of is if % was in the encryption. As far as I've been able to tell and test, I have not come across it so I don't believe would be.

Also should update setup.sh to include the usage for:
`$0 email update <email> <password>`

and add the case:
```
update)
    shift
    _docker_image editmailuser $@
    ;;
```

Let me know if I can make a pull request for anything to help.

**Comment by Josef-Friedrich** [comment]
@marceloschmidt Thank you for submitting your script! Can you please write a test. Writing tests with [bats](https://github.com/sstephenson/bats) is so nice.

**Comment by marceloschmidt** [comment]
I'll have to learn some bash programming 😂 but give me a few days and I'll add some tests! Thanks!

**Comment by tomav** [comment]
Yeah, no problem @marceloschmidt

**Comment by tomav** [comment]
Hi @marceloschmidt, did you get a chance to look at `bats`integration test?
We can help you if necessary. Feel free to ask. Tests are important to make this robust to changes.

**Comment by tomav** [comment]
Fixed by #413

**Pull request closed without merging**
