### PR TITLE
Ignore commented or empty lines from config file

### PR DESCRIPTION
**Pull request by Zehir**
Affected files:

* `config/postfix-virtual.cf`
* `config/postfix-master.cf`

### CODE REVIEW

**Comment by tomav** [comment]
Could you add a test on it?
Few users had this problem. Let's be sure that it will work, ever ;-)

**Comment by Zehir** [comment]
It's will not work with this type of comments:
`mynetworks=127.0.0.0/8 # comment`
Then I dont know what type of test we can make for this

**Comment by Josef-Friedrich** [comment]
@Zehir If I understand your PR right, all lines containing a comment are ignored? Why not simply clean out all comments? So the `docker-mailserver` admins can write as many comments in`postfix-*` they want. Here a sample code snippet:

```sh
#! /bin/sh

while read line; do
	line=$(echo $line | sed -E 's/#.*//')
	[ -n "$line" ] && echo $line
done <<EOF
postmaster@example.com postmaster # comment
info@example.com       joe # comment
sales@example.com      jane # comment
# Uncomment entry below to implement a catch-all address
# @example.com         jim
EOF
```

Output:

```
postmaster@example.com postmaster
info@example.com joe
sales@example.com jane
```

**Comment by Zehir** [comment]
Yes you can use this too. Add your code in a pull request and reject this one.

**Comment by tomav** [comment]
@Josef-Friedrich What should we do with this PR?

**Comment by Josef-Friedrich** [comment]
I tried a different approach there: https://github.com/Josef-Friedrich/docker-mailserver/commit/c5ecd73e1e5828d483a36433155f796542513e47
I ran into testing issues. Any suggestions? Maybe I can have a look at this on the weekend.

**Comment by tomav** [comment]
Hi @Zehir / @Josef-Friedrich, any update this?

**Comment by tomav** [comment]
Will use https://github.com/Josef-Friedrich/docker-mailserver/commit/c5ecd73e1e5828d483a36433155f796542513e47 when ready. Feel free to ask if you need help.

**Pull request closed without merging**
