### PR TITLE
Modify the Dockerfile attempting to use alpine

### PR DESCRIPTION
**Pull request by KyleOndy**
# BROKEN & INCOMPLETE

So this is the core of what I had when working towards alpine.

I didn't commit my changes to `start-mailserver.sh` as my images never got that far. My main concern was getting dovecot to start.

Trying to start it fails because alpines [init systen](http://wiki.alpinelinux.org/wiki/Alpine_Linux_Init_System) `OpenRC` [does not exist](https://github.com/gliderlabs/docker-alpine/issues/42) in the alpine's docker image.

### CODE REVIEW

**Comment by KyleOndy** [comment]
@mgansler Here is what I was working on.

Discussion relates to #109

**Comment by 00angus** [comment]
@KyleOndy that one you posted is an important step: from here we can better understand what we can obtain with alpine.

To dig further I've a question on your quote:
 
> My main concern was getting dovecot to start. [snip] Trying to start it fails because alpines init systen OpenRC does not exist in the alpine's docker image.

From my experience, on a docker image we don't need an init system. If you take a look to a running instance of docker-mailserver:master o v2 you will not find an init process.
In fact, to startup dovecot it's sufficient to run:

`/usr/sbin/dovecot -c /etc/dovecot/dovecot.conf`

Given a proper setup/config, it will work without an init system. The same apply to postfix.

So, you have already included dovecot in the dockerfile with apline (which I've not tested right now). What's wrong with running it if you apply docker-mailserver:v2 setup ?

**Comment by KyleOndy** [comment]
I am having difficulty reproducing the issues I were having. 

I may dig into this tonight again.

**Comment by KyleOndy** [comment]
I think I might be making slow progress. By removing everything else, I got dovecot to start. Test still fail all over, but I'm going to see what I can do.

**Comment by KyleOndy** [comment]
So this is where I am getting hung up things.

Dovecot stats fine
```
Regenerating postfix 'vmailbox' and 'virtual' for given users
user 'user1' for domain 'localhost.localdomain' with password '********'
user 'user2' for domain 'otherdomain.tld' with password '********'
Fixing permissions
Creating /etc/mailname
 * Starting dovecot services
Listing users
user1@localhost.localdomain
user2@otherdomain.tld
Starting...
Apr 22 22:56:57 master: Info: Dovecot v2.2.20 (46a35dcdb936) starting up for imap, pop3, lmtp
Apr 22 22:56:58 ssl-params: Info: Generating SSL parameters
Apr 22 22:56:59 ssl-params: Info: SSL parameters regeneration completed
```

When I run the test suite it hangs.
```
checking imap: server is ready with STARTTLS
```

Looking at the test file the command for this test is
```
docker exec mail /bin/bash -c "nc -w 5 -i 10 0.0.0.0 143 | grep '* OK' | grep 'STARTTLS' | grep 'ready'"
```

which when run manually yields 
```
* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
```

So the test should pass! Yay. However netcat never terminates the connection. I don't know if this is because of the version alpine is using or what.

**Comment by KyleOndy** [comment]
It also seems the text fixtures are returning an error code of `1`, causing the make command to fail.

Could it be the busybox version of `nc` causing these problems?

**Comment by KyleOndy** [comment]
`50 tests, 32 failures` I think I'm done for the night.

**Comment by KyleOndy** [comment]
`50 tests, 27 failures`

**Pull request closed without merging**
