### PR TITLE
Allow user to provide Amavis configuration

### PR DESCRIPTION
**Pull request by keslerm**
This will allow the user to provide custom Amavis configuration file.

Pretty straightforward.

### CODE REVIEW

**Comment by keslerm** [comment]
Related to #298

**Comment by tomav** [comment]
Hi @keslerm, could you resolve the conflict? I'll merge as soon its ready.
Thank you.

**Comment by keslerm** [comment]
Updated

**Comment by tomav** [comment]
Thanks, perhaps this needs to be explained in a Wiki page.

**Comment by kachkaev** [comment]
Hi @keslerm, could you please add a few lines to wiki about how to configure amavis? I guess we can now mount some new volume for this to happen, but it's not 100% clear what to do to the newbies like me.

Being more specific, I'm interested in making the container as lite as possible to use the server as a 'reverse-proxy' for emails (i.e. people 'talk' to abcd@example.com and I manage everything with a gmail account). My gut-feeling suggests that I can somehow switch off all spam & virus checking and leave only dkim signatures by means of some custom amavis config (switching dkim off too is probably a bad idea). Feel free to correct me if my assumptions are wrong.

My mail 'reverse-proxy' works already, I just see that some incoming mail is being marked as spam and is therefore not passed upstream to google. What I'd like is to have gmail handle all that. Some users of this great docker image are likely to have the same intention, so your contribution to wiki will be appreciated by many!

**Pull request merged**
