### PR TITLE
Environment variable for amavis subject tag

### PR DESCRIPTION
**Pull request by elbracht**
Ref: #589

Environment variable to change the amavis tag `sa_spam_subject_tag` outside the container .

### CODE REVIEW

**Comment by tomav** [comment]
Hi @elbracht, don't forget integration tests.

**Comment by elbracht** [comment]
@tomav do you have an idea why I can’t use a string as environment variable? If I use a number as environment variable in `Makefile` it works.

Works:

```
-e SA_SPAM_SUBJECT=10.0 \
```

Don’t work:

```
-e SA_SPAM_SUBJECT="SPAM: " \
```

**Comment by tomav** [comment]
Still 2 errors in this build. How can we move forward?

**Comment by elbracht** [comment]
@tomav I can’t use a string as environment variable to update the `$sa_spam_subject_tag` in `start-mailserver.sh`. With a number or a fixed value as environment variable it works.

number (Makefile):

```
docker run -d --name mail \
...
-e SA_SPAM_SUBJECT=10.0 \
```

fixed value (start-mailserver.sh):

```
sed -i -r 's/^\$sa_spam_subject_tag (.*);/\$sa_spam_subject_tag = fixed value';/g' /etc/amavis/conf.d/20-debian_defaults
```

**Comment by tomav** [comment]
The error is [here](https://github.com/elbracht/docker-mailserver/blob/5b9908bd04cecc49366c842e26af37393e4acedb/test/tests.bats#L438)

**Comment by elbracht** [comment]
@tomav I know that the test failed on this line but this is not the problem. 

I think the problem is that the environment variable is not passed to the start script `start-mailserver.sh` ([here](https://github.com/elbracht/docker-mailserver/blob/5b9908bd04cecc49366c842e26af37393e4acedb/Makefile#L30)).

Or the script doesn't write the variable to the config file ([here](https://github.com/elbracht/docker-mailserver/blob/5b9908bd04cecc49366c842e26af37393e4acedb/target/start-mailserver.sh#L936)).

**Comment by tomav** [comment]
I have an error with `sed` when trying to run the line for subject tag configuration.
This seems to work better:

```
sed -i -r 's/^\$sa_spam_subject_tag (.*);/\$sa_spam_subject_tag = '"'$SA_SPAM_SUBJECT'"';/g'
```

Let me know if it works for you.

**Comment by elbracht** [comment]
@tomav Nice! 👍 

Now the local tests have been passed.

**Comment by tomav** [comment]
Here we are!

**Comment by jholster** [comment]
Sorry for reopening this, but it's not clear for me how to disable the subject rewrite entirely. If SA_SPAM_SUBJECT is empty/undefined, it seems to default to ***SPAM***. I would like to keep my subject unchanged, because I'm moving spams to separate folder.

**Comment by johansmitsnl** [comment]
@jholster maybe add a " " space in the variable might fit your needs.

**Comment by jholster** [comment]
@johansmitsnl Tried that, didn't help, maybe the configuration parsers trims the lines? Anyway, sounds  like hack. Can we additionally have SA_ENABLE_SPAM_SUBJECT_REWRITE boolean variable?

I think it's very common case to move spam messages into separate spam folder. Once in a while I skim through my spams and move false positives to inbox/archive folder (to teach SpamAssassin). But the moved messages will have "***SPAM***" in subject line forever, which is kind of ugly.

**Comment by elbracht** [comment]
@jholster The following environment variable should solve your problem:

```
-e SA_SPAM_SUBJECT=undef
```

**Comment by jholster** [comment]
@elbracht Thanks, that finally solved the issue. If anyone else wonders how the .env parser distinguish between undef and "undef" – it does not, "undef" is just a magic string, see [here](https://github.com/tomav/docker-mailserver/blob/master/target/start-mailserver.sh#L1217).

**Pull request merged**
