### PR TITLE
Update start-mailserver.sh

### PR DESCRIPTION
**Pull request by iNDicat0r**
Argument type should be -e and not -P

### CODE REVIEW

**Comment by erik-wramner** [comment]
I think you are wrong. Check http://www.postfix.org/postconf.1.html. For updating `master.cf` parameters it should be `-P`. For `main.cf` it should be `-e`. The block you have changed is for `master.cf`.

**Comment by iNDicat0r** [comment]
> I think you are wrong. Check http://www.postfix.org/postconf.1.html. For updating `master.cf` parameters it should be `-P`. For `main.cf` it should be `-e`. The block you have changed is for `master.cf`.

The -P option doesn't accept $line of type "key=value" and therefore when you try to load a master.cf from the `config` folder it throws an error.

I tried to change some values of postfix and had them under `postfix-master.cf` and then tried to inspect the logs and saw that postfix -P $line was throwing errors.

**Comment by erik-wramner** [comment]
Right. Perhaps we need both `-P` and `-e` or something, I need to check. That code is quite old though, really surprising if it has been wrong all that time. Of course, not many are overriding those options.

**Comment by iNDicat0r** [comment]
> Right. Perhaps we need both `-P` and `-e` or something, I need to check. That code is quite old though, really surprising if it has been wrong all that time. Of course, not many are overriding those options.

The error I was getting was: 

```
postconf -Pe or -PX requires service_name/type/parameter
```

and i had the following value in my postfix-master.cf:
```
smtpd_client_connection_count_limit = 500
```

**Comment by erik-wramner** [comment]
This is poorly documented, but I think you are simply using the wrong format. The postfix-master.cf does not use `name=value`, it uses `service_name/type/name=value`. For example `127.0.0.1:10025/inet/smtpd_soft_error_limit=1002` results in `postconf -P 127.0.0.1:10025/inet/smtpd_soft_error_limit=1002` which works.

If you enter the container (`docker exec -it mail /bin/bash`) and run `postconf -P` it will show the active options with the correct format except that there are spaces that must be removed.

**Comment by erik-wramner** [comment]
I've updated the documentation in the FAQ. Are you happy with that?

**Comment by iNDicat0r** [comment]
Alright thank you

**Pull request closed without merging**
