### PR TITLE
Relay support & duplicate DKIM fix

### LINKED ISSUE #86: Duplicate DKIM signature
Outgoing emails have two identical DKIM signatures; this makes both of them invalid and triggers spam filters (the message gets marked as spam on [MailTester](https://www.mail-tester.com) and Outlook).

Container log after sending the mail from an IMAP client:
```
Feb 26 16:43:41 mail postfix/submission/smtpd[884]: connect from <IP>
Feb 26 16:43:42 mail postfix/submission/smtpd[884]: 5F3EDEEC: client=<IP>, sasl_method=PLAIN, sasl_username=<USERNAME>
Feb 26 16:43:42 mail postfix/cleanup[930]: 5F3EDEEC: message-id=<>
*** Feb 26 16:43:42 mail opendkim[532]: 5F3EDEEC: DKIM-Signature field added (s=mail, d=<DOMAIN>)
Feb 26 16:43:42 mail opendmarc[543]: 5F3EDEEC: <DOMAIN> none
Feb 26 16:43:42 mail postfix/qmgr[645]: 5F3EDEEC: from=<<USERNAME>>, size=630, nrcpt=1 (queue active)
Feb 26 16:43:44 mail postfix/smtpd[935]: connect from localhost[127.0.0.1]
Feb 26 16:43:44 mail postfix/smtpd[935]: 5B96DEED: client=localhost[127.0.0.1]
Feb 26 16:43:44 mail postfix/cleanup[930]: 5B96DEED: message-id=<20160226164344.5B96DEED@<DOMAIN>>
*** Feb 26 16:43:44 mail opendkim[532]: 5B96DEED: DKIM-Signature field added (s=mail, d=<DOMAIN>)
Feb 26 16:43:44 mail postfix/qmgr[645]: 5B96DEED: from=<<USERNAME>>, size=1512, nrcpt=1 (queue active)
Feb 26 16:43:44 mail postfix/smtpd[935]: disconnect from localhost[127.0.0.1]
Feb 26 16:43:44 mail amavis[713]: (00713-03) Passed CLEAN {RelayedOpenRelay}, [<IP>]:22206 [<IP>] <<USERNAME>> -> <web-etc@mail-tester.com>, Queue-ID: 5F3EDEEC, mail_id: ueBCPyxxjcJe, Hits: 1.093, size: 1032, queued_as: 5B96DEED, 1643 ms
Feb 26 16:43:44 mail postfix/smtp[931]: 5F3EDEEC: to=<web-etc@mail-tester.com>, relay=127.0.0.1[127.0.0.1]:10024, delay=2.1, delays=0.46/0.01/0.01/1.6, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 5B96DEED)
Feb 26 16:43:44 mail postfix/qmgr[645]: 5F3EDEEC: removed
Feb 26 16:43:44 mail postfix/smtp[936]: Untrusted TLS connection established to mail-tester.com[94.23.206.89]:25: TLSv1.2 with cipher AECDH-AES256-SHA (256/256 bits)
Feb 26 16:43:44 mail postfix/smtp[936]: 5B96DEED: to=<web-etc@mail-tester.com>, relay=mail-tester.com[94.23.206.89]:25, delay=0.58, delays=0.05/0.01/0.48/0.03, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as B4CB3A9D55)
Feb 26 16:43:44 mail postfix/qmgr[645]: 5B96DEED: removed
```

Notice how the mail gets signed twice by `opendkim`.
I confirmed the issue on every client I tried, including Airmail for OS X, Gmail for Android and PHPMailer.

### PR DESCRIPTION
**Pull request by Chris54721**
As #83 with integration tests.
Also fixes #86.

### CODE REVIEW

**Comment by Chris54721** [comment]
@tomav Looks like the Travis build froze - tests worked fine locally.

**Comment by tomav** [comment]
Don't worry, it will pass, or I will restart it.

**Comment by tomav** [comment]
Green! Thank you @Chris54721.

**Comment by robertdolca** [comment]
Thank you @Chris54721

**Comment by Chris54721** [comment]
:ok_hand: Now emails should pass basically any spam filter!


image

**Pull request merged**
