### PR TITLE
Remove $myhostname from mydestination when ldap enabled

### PR DESCRIPTION
**Pull request by codejamninja**
Fixes issue #1722

### CODE REVIEW

**Comment by aendeavor** [comment]
You will just need to escape the `sed` command for shellcheck with

``` BASH
# shellcheck disable=SC2016
sed ...
```

**Comment by codejamninja** [comment]
Ok I just added `shellcheck disable=SC2016`.

**Comment by aendeavor** [comment]
Alright, the shellcheck tests are now passing. We are now seeing an odd behavior with the tests known from another PR. This is not your fault - we will need to investigate on this. When this is resolved, I think we can merge this PR.

---

@erik-wramner do you have any idea why the tests cannot pull certain images, reaching the pull limit due to retries? Even though we are migrating away from TravisCI to GH actions, this is not complete yet, so we will most likely want to merge another PR or two with Travis.

**Comment by williamdes** [comment]
Do you think this would solve this error ?
```
Jan  1 20:19:56 mail postfix/smtpd[8609]: NOQUEUE: reject: RCPT from outbyoip5.pod13.usw2.zdsys.com[192.161.151.5]: 554 5.7.1 <contact@xxxxxxxxxxxxxxxxxxx.org>: Relay access denied; from=<support@cloudflare.com> to=<contact@xxxxxxxxxxxxxxxxxxx.org> proto=ESMTP helo=<outbyoip5.pod13.usw2.zdsys.com>
```

With my ldap setup the final account has multiple aliases on the same domain and an alias to another domain. And when receiving emails it does throw `Relay access denied`

**Comment by aendeavor** [comment]
> Do you think this would solve this error ?
> 
> ```
> Jan  1 20:19:56 mail postfix/smtpd[8609]: NOQUEUE: reject: RCPT from outbyoip5.pod13.usw2.zdsys.com[192.161.151.5]: 554 5.7.1 <contact@xxxxxxxxxxxxxxxxxxx.org>: Relay access denied; from=<support@cloudflare.com> to=<contact@xxxxxxxxxxxxxxxxxxx.org> proto=ESMTP helo=<outbyoip5.pod13.usw2.zdsys.com>
> ```
> 
> With my ldap setup the final account has multiple aliases on the same domain and an alias to another domain. And when receiving emails it does throw `Relay access denied`

Possibly, but the best way of finding out would be to clone @codejamninja's repo, check out the branch and build the image yourself. Then test it. This way you can be sure.

**Comment by williamdes** [comment]
Well I added this to user patches in https://github.com/desportes/infrastructure/commit/4ce4d76379e5c888fa1a1472323f89a670f55066 and the test suite still passes.
I am writing a test for (ex/in)ternal mail domains that and will let you know in some hours

**Comment by williamdes** [comment]
My internal test https://github.com/desportes/infrastructure/commit/4004c04001f49960141141dd829f5f2950a398d0 showed that users from the mail server can send emails to users on different domains on the same server.
Only users from another mail server have the error I reported.
See: https://blog.tinned-software.net/setup-postfix-for-multiple-domains/

**Review by williamdes — APPROVED** [review]
Tested on my CI and tests without problems using LDAP

**Comment by aendeavor** [comment]
So this solves two problems at once? Nice:)

**Comment by williamdes** [comment]
> So this solves two problems at once? Nice:)

I did not explain myself well, for me it does not solve any real problem but it says on https://postfix.traduc.org/index.php/VIRTUAL_README.html in French `NEVER list a virtual alias domain in the mydestination domain list!`
So this fix LGTM, it does not introduce regressions on my LDAP setup.

And for the error I reported I think this is the issue #1694 on ldap setups

**Comment by codejamninja** [comment]
What needs to be done to get this pull request accepted?

**Comment by aendeavor** [comment]
> What needs to be done to get this pull request accepted?

Currently, this PR cannot be merged in this repository, but not due to us, but due to TravisCI which has become unusable. We are working on this in https://github.com/docker-mailserver/docker-mailserver as fast as possible. This should be done in the next few days. When the migration to the new repository has finished, this PR will just need to be re-opened over there and can then be merged.

**Comment by codejamninja** [comment]
Ok, thanks

**Comment by codejamninja** [comment]
I created the following pull request at https://github.com/docker-mailserver/docker-mailserver.

https://github.com/docker-mailserver/docker-mailserver/pull/8

**Comment by aendeavor** [comment]
> I created the following pull request at https://github.com/docker-mailserver/docker-mailserver.
> 
> 
> 
> https://github.com/docker-mailserver/docker-mailserver/pull/8

Alright. Then this can be closed here. Sorry it takes a bit longer - the first PR is 3000 LOC.

**Pull request closed without merging**
