### PR TITLE
switch to SHA512

### PR DESCRIPTION
**Pull request by Crafter6432**
I removed test/auth/smtp-auth-cram-md5.txt because I don't think that CRAM-MD5-AUTH will work anymore, if we don't have a MD5 hash to compare against.

### CODE REVIEW

**Comment by Crafter6432** [comment]
Any idea how to fix this test ?

**Comment by tomav** [comment]
Yes, the test is `diff test/config/example.postfix-accounts.cf test/config/postfix-accounts.cf`
So you have to update `test/config/example.postfix-accounts.cf` as reference with `SHA512` passwords.
Default clear password should be `mypassword`.

**Comment by Crafter6432** [comment]
SHA512-CRYPT is salting the passwords, which means the hash is always different and thus not comparable.

**Comment by tomav** [comment]
Thank you. I update the Wiki.

**Pull request merged**
