### PR TITLE
Change Email-Folder to /var/mail/%d/%u/mails

### PR DESCRIPTION
**Pull request by evilstiefel**
This solves the issue that when running managesieve, the .sieve-folder shows up as subscribable for IMAP clients but will produce an error when selecting. Mainly to remove clutter and to follow dovecot recommendations on not setting the same directory for user home and user mail.

This should not be merged as of yet, because it will break existing mail-stores. Hopefully though, this pull request will let me automatically run the travis-suite to check if the changes are safe for new installations.

Later, if the request is desirable, we could add a config flag like the many other's that already exist,

### CODE REVIEW

**Comment by evilstiefel** [comment]
I noticed that the bats test references the home directory directly, so I need to update these tests (next to preparing a configurable flag).

Some background on why the home directory should be different to the mail directory for virtual users:
https://wiki2.dovecot.org/VirtualUsers/Home

**Comment by johansmitsnl** [comment]
@evilstiefel why use a configurable flag? A migration script in the startup script would also work and it will make a permanent change to the structure.
Not sure what the admins think of this idea though.

**Comment by Fmstrat** [comment]
I think this could be handled in the `user_attrs` option in the dovecot configuration. This is a request in my LDAP issue, too: https://github.com/tomav/docker-mailserver/issues/680

**Comment by johansmitsnl** [comment]
@evilstiefel any progress on this PR?

**Comment by evilstiefel** [comment]
The changes to the tests and files are minimal and complete, as far as I'm concerned. I've tested this extensively and used it on my own setup for quite some time. I cannot debug the LDAP failure in the travis environment, since I'm not knowledgeable in that area. It seems to me that the user folder is also specified in the directory and I am unsure how to change the file.

As to the issue how best to implement this if the PR is desirable, either via a configurable flag or just migrating existing folders in the case of anybody upgrading from an image with the "old" folder-structure, that's up to the maintainers (I see that as a "political" decision).

Since then, I've switched to another setup to be honest, since I didn't feel there was much feedback or activity either here or on the gitter chat.

**Comment by johansmitsnl** [comment]
Clear. I'll patch up your pr.
Will close yours and open a new one from my repository that has LDAP support. I did already work on the LDAP part.
Tomav doesn't have much time at the moment. Gained access to the repo and have some spare time to spend on it. 
Suggestions are always welcome. Thanks for you effort on testing and his pr.

**Pull request closed without merging**
