### PR TITLE
Fix shebangs

### PR DESCRIPTION
**Pull request by williamdes**
- Fixes shebangs

### CODE REVIEW

**Comment by aendeavor** [comment]
I do not see how this fixes anything - don't get me wrong, I do not want to impolite, but the choices of shebangs and readme fences were on purpose. I think they are fine they way they are.

**Comment by williamdes** [comment]
Okay, but for me the readme fences are incorrect

Please let me know why some script use a space and some do not so I can revert that :)

**Comment by aendeavor** [comment]
This project uses all-uppercase readme fences with a space between the three hyphens. There are still some inconsistencies - feel free to resolve them. The scripts should all use `#! /SOME/PATH`, i.e. with a space after `#!`. If there are inconsistencies too, I'd be happy to see them resolved too.

**Comment by williamdes** [comment]
> This project uses all-uppercase readme fences with a space between the three hyphens.

But why and where does it come from, it just feels strange to me

Okay I will revert and fix the non spaced files

**Comment by aendeavor** [comment]
> > This project uses all-uppercase readme fences with a space between the three hyphens.
> 
> But why and where does it come from, it just feels strange to me
> 
> Okay I will revert and fix the non spaced files

I guess personal preference. To me, it feels strange to do it in another way. I just feel like this is clean and I would not really like to change whats stable there:) I'd like the readme fences to stay as they are.

**Review by aendeavor — APPROVED** [review]

**Pull request merged**
