### PR TITLE
/etc/opendkim/TrustedHosts creation if missing

### PR DESCRIPTION
**Pull request by auguster**
Following issue #132, the script `start-mailserver.sh` now creates and populates `/etc/opendkim/TrustedHosts` with localhost information.

This allow for mounting an empty directory from the host for DKIM data persistence.

### CODE REVIEW

**Comment by tomav** [comment]
Thank you!

**Comment by auguster** [comment]
You're welcome, it wasn't hard at all ^^

**Comment by aguerrave** [comment]
Hello for all, Excellent work, you beginning to test, you have a howto?

**Comment by auguster** [comment]
@aguerrave I did some local test, it seems to work fine. As you can see the code is rather simple so I think it's safe ;)

For the howto, just mount an empty directory from host for `/etc/opendkim` and you'll see that the servers create a basic `/etc/opendkim/TrustedHosts` with localhost informations:

```
localhost
127.0.0.1
```
The discussion open this is mainly in issue #132 for extended details.

**Comment by aguerrave** [comment]
Ok 
i have a domain valid for test

**Pull request merged**
