### PR TITLE
Added  reject_sender_login_mismatch

### PR DESCRIPTION
**Pull request by TechnicLab**
Added reject_sender_login_mismatch parameter to prevent users from sending email using arbitrary email address. #811

### CODE REVIEW

**Comment by 17Halbe** [comment]
Hmm.. I might got this wrong, but don't you need a mapping file to make that work? Is this really denying a logged in user to spoof it's FROM address? I always had to implement a mapping file.

Which would probably look like:
main.cf:
```
...
smtpd_sender_login_maps = pcre:mapping.file
...
```
and the 
mapping.file:
```
/^(.*)$/   ${1}
```

All from memory, but it took me quite a while back than to figure that out.. So it sticks! ;) 
And yes, this would map every user to only his mailaccount.

**Comment by TechnicLab** [comment]
Great idea! It is not working in my implemention, I actually created another fork request but there was a problem with requipment of mapping users. Could you fix this please?

**Comment by 17Halbe** [comment]
I will fix it, if you implement a test for it! ;)

**Comment by TechnicLab** [comment]
I am not familiar with tests that are used in this image, but I could try...

**Comment by TechnicLab** [comment]
https://github.com/tomav/docker-mailserver/pull/825 - here is another pull request. Unfortunately forking only with ldap.

**Comment by 17Halbe** [comment]
Oh, great find! :) That would probably be replaceable with my idea.. I'll have a look

**Pull request merged**
