### PR TITLE
WIP / HELP WANTED: Refactord all scripts, adding shellcheck to travis; refactoring a few other files on the fly

### PR DESCRIPTION
**Pull request by aendeavor**
# This is a bigger one

This was a lot of work. Please consider this before arguing. I know it's kind of big, but I think it's worth the hassle.

## First things first

- [ ] This PR **obsoletes** #1228 and #1550. Please close these issues.
- [x] This PR is based on both #1595 and #1596. They will need to be merged first. (#1595 is already.)

## Help needed

The current problem I'm working on arises from a (locally executed) test:

``` BASH
 ✗ checking spoofing: accepts sending as alias
   (from function `assert_success' in file test/test_helper/bats-assert/src/assert.bash, line 114,
    in test file test/tests.bats, line 1503)
     `assert_success' failed

   -- command failed --
   status : 1
   output :
   --
```

This is kind of ridiculous:

``` BASH
not ok 2 check helper function: _sanitize_ipv4_to_subnet_cidr
 (from function `assert_output' in file test/test_helper/bats-assert/src/assert.bash, line 239,
  in test file test/helper_functions.bats, line 9)
   `assert_output "0.0.0.0/0"' failed
 ./target/helper_functions.sh: line 39: mapfile: -d: invalid option
 mapfile: usage: mapfile [-n count] [-O origin] [-s count] [-t] [-u fd] [-C callback] [-c quantum] [array]
 ./target/helper_functions.sh: line 29: & 0: syntax error: operand expected (error token is "& 0")
 ./target/helper_functions.sh: line 29: & 0: syntax error: operand expected (error token is "& 0")
 ./target/helper_functions.sh: line 29: & 0: syntax error: operand expected (error token is "& 0")
 ./target/helper_functions.sh: line 29: & 0: syntax error: operand expected (error token is "& 0")
 
 -- output differs --
 expected : 0.0.0.0/0
 actual   : .../0
 -- 
```

Using this function locally works perfect. The use of `mapfile -d '.' ...` in other places does not seem to throw an error. This seems to be related with the version of Bash used**?** I'm on Bash 5.0.17.

I would like to receive some help here.

This is rather interesting: I do not get this error locally too.

``` BASH
not ok 260 checking setup.sh: setup.sh email add and login
 (from function `assert_output' in file test/test_helper/bats-assert/src/assert.bash, line 239,
  in test file test/tests.bats, line 1251)
   `assert_output "passdb: setup_email_add@example.com auth succeeded"' failed
 
 -- output differs --
 expected : passdb: setup_email_add@example.com auth succeeded
 actual   : passdb: setup_email_add@example.com auth failed
 --
```

## Changes & Rationale

I made this PR to include `shellcheck` and to make all the scripts more **robust**. **I believe the latter to be especially important**. Therefore, I refactored all scripts under `target/` (which was a lot of work). I furthermore extended `CONTRIBUTING.md` with necessary coding style guidelines, and linking to it from `README`. This accounts for the biggest portion of this PR.

Travis should now use the shellcheck option and apply it via make.

I refactored the `Makefile` too, to make it verbose where it should be, and less verbose where it's appropriate.

## Important

I'd really like to see some contributions in the form of either objective opinions or (better :D) code contributions to fix possible errors.

### CODE REVIEW

**Comment by erik-wramner** [comment]
I really appreciate all the work you have put into this and it is absolutely worthwhile. However, based on previous similar attempts that have lost speed after a while and our limited review capacity I would suggest splitting the massive PR into many small parts, where we can merge and get the benefits from one change without having to wait for all of them to go through.

That is just a suggestion. I'll get around to this eventually regardless, but I'm short on time as always and it tends to be easier to merge many small changes on at a time.

**Comment by aendeavor** [comment]
@erik-wramner You're right. I came  up with this: All changes not related to `start-mailserver.sh` will be thrown into another PR. Those account for the minority of changes. The changes to `start-mailserver.sh` will receive their own PR. I will need #1596 for this to be merged though. How fast can you arrage this?

**Comment by aendeavor** [comment]
PS: I read about the limited review capacity. I'd like to help there, but I'd need to be a collaborator for this (or don't I?). What can we do abut this?

**Comment by erik-wramner** [comment]
It is merged now. You would need access from @tomav to actually do merges, but you're welcome to help with reviews of other PRs if you like. Not to mention answering questions, that is where I spend the bulk of my time.

**Comment by aendeavor** [comment]
How would I go about contacting @tomav,  @erik-wramner ?

My rationale is this: I'm using the server and wan't it to be stable. Therefore I'd like to collaborate, answer questions and review/manager PRs :)

**Comment by aendeavor** [comment]
Closing this PR as #1600 will come up soon.

**Comment by tomav** [comment]
@aendeavor thanks for this very good work and welcome onboard!

**Pull request closed without merging**
