### PR TITLE
RFC: add option for user to change password

### PR DESCRIPTION
**Pull request by jurekbarth**
It's an easy interface to change the password. It's a small server written in Go. There're no shell scripts involved and it only works with SHA512 encryption at the moment. 
If you startup the server you should also expose port 8000 or run it through a proxy like traefik or nginx.
There's a webinterface included which is accessible on `http://localhost:8000`. The API Endpoint is located on `http://localhost:8000/change` which listens for POST Requests. The body should be JSON encoded. And the object should look something like this:
```
{"Mail":"test@domain.tld", "CurrentSecret": "yoursecret", "NewSecret": "yournewsecret"}
```

There's something like fail2ban in place.

### CODE REVIEW

**Comment by johansmitsnl** [comment]
This looks good, could you add tests and also check why the current tests fail?

**Comment by johansmitsnl** [comment]
Tests pass, could you add a test for a password change to also test functionality?
Then I can merge it.

**Comment by jurekbarth** [comment]
Ok, how do they pass now? I‘m having trouble running tests without crashing my docker daemon on mac os. But i will add tests :)

**Comment by mwlczk** [comment]
@jurekbarth by saying "testspass" johan most likely ment "you did not brake anything which was working/tested until now".
You need most likely >= 4GB of RAM only for the docker engine to run the tests smoothly.

**Comment by johansmitsnl** [comment]
@jurekbarth sometimes Travis is to busy and test fail due to the load. I ran it again to check if it works.
It did because no changes to the current postfix setup was made.
As @mwlczk told you need some ram to run tests locally.

**Comment by thiesschneider** [comment]
any news here?

**Comment by johansmitsnl** [comment]
@thiesschneider it is missing tests, could you jump in to assist?

**Comment by jurekbarth** [comment]
@thiesschneider i could not get the tests running locally a year ago, if you could get them up and running i would love to get this finally done :)

**Comment by johansmitsnl** [comment]
See also #950

**Comment by ThisIsQasim** [comment]
Has there been any update on this?

**Comment by erik-wramner** [comment]
This is a very nice feature, but why run it inside the main container? The account file is in a volume, so this might as well be a stand-alone docker container? Either in another repo with a reference from the readme or by all means in this repo.

To add it as an official feature in this repo I agree with @johansmitsnl that we need some tests. The Travis tests are green now and should work locally on Linux hosts.

**Comment by ThisIsQasim** [comment]
Just tried running the mentioned go service and it crashes with the following trace
 
```
PANIC: runtime error: slice bounds out of range [:-1]
goroutine 20 [running]:
github.com/urfave/negroni.(*Recovery).ServeHTTP.func1(0x7f44ace6c028, 0xc0001d0fe0, 0xc000014320, 0xc000156700)
	/go/src/github.com/urfave/negroni/recovery.go:164 +0xeb
panic(0x7e47a0, 0xc0001ece00)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
main.findUser(0xc000151910, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/app/gocrypt.go:55 +0x4cc
main.changePassword(0x7f44ace6c028, 0xc0001d0fe0, 0xc000156700, 0x0, 0x0, 0x0)
	/app/gocrypt.go:115 +0x1c5
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc0000ae180, 0x7f44ace6c028, 0xc0001d0fe0, 0xc000156700)
	/go/src/github.com/julienschmidt/httprouter/router.go:434 +0x722
github.com/urfave/negroni.Wrap.func1(0x7f44ace6c028, 0xc0001d0fe0, 0xc000156700, 0xc00000e520)
	/go/src/github.com/urfave/negroni/negroni.go:55 +0x4d
github.com/urfave/negroni.HandlerFunc.ServeHTTP(0xc00000e4e0, 0x7f44ace6c028, 0xc0001d0fe0, 0xc000156700, 0xc00000e520)
	/go/src/github.com/urfave/negroni/negroni.go:29 +0x4e
github.com/urfave/negroni.middleware.ServeHTTP(...)
	/go/src/github.com/urfave/negroni/negroni.go:47
main.(*BadActorMiddleware).ServeHTTP(0xc000012e20, 0x7f44ace6c028, 0xc0001d0fe0, 0xc000156700, 0xc00000e540)
	/app/gocrypt.go:217 +0x10d
github.com/urfave/negroni.middleware.ServeHTTP(...)
	/go/src/github.com/urfave/negroni/negroni.go:47
github.com/urfave/negroni.(*Static).ServeHTTP(0xc0000f7b60, 0x7f44ace6c028, 0xc0001d0fe0, 0xc000156700, 0xc00000e560)
	/go/src/github.com/urfave/negroni/static.go:34 +0x7ba
github.com/urfave/negroni.middleware.ServeHTTP(...)
	/go/src/github.com/urfave/negroni/negroni.go:47
github.com/urfave/negroni.(*Static).ServeHTTP(0xc0000f7ad0, 0x7f44ace6c028, 0xc0001d0fe0, 0xc000156700, 0xc00000e580)
	/go/src/github.com/urfave/negroni/static.go:34 +0x7ba
github.com/urfave/negroni.middleware.ServeHTTP(...)
	/go/src/github.com/urfave/negroni/negroni.go:47
github.com/urfave/negroni.(*Logger).ServeHTTP(0xc0000f7560, 0x7f44ace6c028, 0xc0001d0fe0, 0xc000156700, 0xc00000e5a0)
	/go/src/github.com/urfave/negroni/logger.go:61 +0x8e
github.com/urfave/negroni.middleware.ServeHTTP(...)
	/go/src/github.com/urfave/negroni/negroni.go:47
github.com/urfave/negroni.(*Recovery).ServeHTTP(0xc000014320, 0x7f44ace6c028, 0xc0001d0fe0, 0xc000156700, 0xc00000e5c0)
	/go/src/github.com/urfave/negroni/recovery.go:208 +0xae
github.com/urfave/negroni.middleware.ServeHTTP(...)
	/go/src/github.com/urfave/negroni/negroni.go:47
github.com/urfave/negroni.(*Negroni).ServeHTTP(0xc0000f7b30, 0x89c320, 0xc000176540, 0xc000156700)
	/go/src/github.com/urfave/negroni/negroni.go:107 +0xfb
net/http.serverHandler.ServeHTTP(0xc00012c000, 0x89c320, 0xc000176540, 0xc000156700)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc00014a280, 0x89cce0, 0xc000152f00)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e
```

**Comment by erik-wramner** [comment]
As it doesn't seem to work and as there have been no updates in ages I will close this. It would be nice with some kind of user interface for changing passwords, but I still think it should be external. There is already a programmatic interface (setup.sh) as well as a file-based interface (the accounts file).

**Comment by ThisIsQasim** [comment]
There was a an empty line in my `postfix-accounts.cf` file. I removed that line and it seems to be working fine now.

And just to help if someone else stumbles across this thread, I am running this daemon in a separate container. With the following `Dockerfile` and an additional service in `docker-compose.yml`. 
```
FROM golang:latest
RUN mkdir /app
ADD ./ /app/
WORKDIR /app
RUN go get github.com/bitly/go-simplejson github.com/jaredfolkins/badactor github.com/julienschmidt/httprouter github.com/tredoe/osutil/user/crypt/sha512_crypt github.com/urfave/negroni
RUN go build -o main .
RUN mkdir /usr/local/bin/update-user-password &&\
         cp -r /app/* /usr/local/bin/update-user-password

EXPOSE 8000/tcp
CMD ["/usr/local/bin/update-user-password/main"]
```
```
  pwdchange:
    build: pwdchange
    ports: 
    - 8000:8000
    restart: always
    volumes:
    - ./config/:/tmp/docker-mailserver/
```

**Pull request closed without merging**
