### PR TITLE
fail2ban handling integrated in setup.sh

### PR DESCRIPTION
**Pull request by 17Halbe**
- calling \"./setup debug fail2ban\" lists all iptable chains whith blocked IPs 
(like: 
Banned in dovecot: 91.200.12.164
Banned in postfix-sasl: 91.200.12.164)
- calling \"./setup debug fail2ban unban xxx.xxx.xxx.xxx [yyy.yyy.yyy.yyy ...]\" unbans/removes those IPs from all jails.
- calling \"./setup debug fail2ban unban\" (without an IP) gives an descriptive error: (You need to specify an IP address. Run "./setup.sh debug fail2ban" to get a list of banned IP addresses.)

### CODE REVIEW

**Comment by 17Halbe** [comment]
Ah, yes, the wiki...
I'll add the info to the wiki page after this PR has been accepted.

**Comment by johansmitsnl** [comment]
Could you add a test for this new feature?

**Comment by 17Halbe** [comment]
will do..

**Comment by 17Halbe** [comment]
Done

**Pull request merged**
