### PR TITLE
Add ENABLE_FAIL2BAN environment variable to enable fail2ban service

### PR DESCRIPTION
**Pull request by 00angus**
Implement #112
Fail2ban is not enabled by default, now.

* Changed/updated Makefile and integration tests
* Changed some grep expressions in the fail2ban tests

### CODE REVIEW

**Comment by KyleOndy** [comment]
The build timed out.

@tomav care to give it a restart?

**Comment by tomav** [comment]
Restarted.

**Comment by 00angus** [comment]
Hmm... stil time out problems:
> Downloading main.cvd [ 50%]
Keeps stopping while downloading updates.

**Comment by tomav** [comment]
Restarted again. I can remove this step in the build but a newly started container will have to `freshclam` manually or wait for the cron to be executed.

**Comment by 00angus** [comment]
I'm experiencing me too big delays while downloading updates for clamav, anyway...
I would prefer to have an image freshly updated - IMHO, if it's possible.
Is it possible to raise the amount of the timeout?

**Comment by tomav** [comment]
It's related to Clamav or Travis. I don't think inscreasing timeout would really solve the problem.

Thanks for your PR.

**Pull request merged**
