### PR TITLE
Remove write access to group and others to Amavis configuration files

### PR DESCRIPTION
**Pull request by artonge**
Remove write access to group and others to Amavis configuration files

Fix: #1446

### CODE REVIEW

**Review by aendeavor — APPROVED** [review]

**Comment by aendeavor** [comment]
I will merge this, but I want to hear @erik-wramner opinion in #1446 first.

**Comment by erik-wramner** [comment]
The chmod affects not only the copied files but any other files that happen to be in the folder as well. I would suggest another approach, see https://github.com/moby/moby/pull/34263. It is now possible to set the permissions and owner in the COPY command in the Dockerfile. If we do that we save one layer in the final image and we don't risk changing existing files in a negative way.

@artonge, can you try that instead, please?

**Review by aendeavor — CHANGES_REQUESTED** [review]
> It is now possible to set the permissions and owner in the COPY command in the Dockerfile. If we do that we save one layer in the final image and we don't risk changing existing files in a negative way.

Exactly why I wanted to hear @erik-wramner on this. Thanks :D

**Comment by erik-wramner** [comment]
Hm, chmod will be supported (https://github.com/moby/moby/issues/34819) but is not there yet. I'll merge this then.

**Pull request merged**
