### PR TITLE
Support for modifying Postfix' master.cf

### PR DESCRIPTION
**Pull request by MadsRC**
Support for modifying Postfix' master.cf, using the  syntax, in postfix-master.cf

Fixes issue-594

### CODE REVIEW

**Comment by tomav** [comment]
@MadsRC any update on this? Thank you.

**Comment by MadsRC** [comment]
Time has been extremely short with an infant at home, so I haven't had the time to dig into the integration testing yet - That, and I'm not familiar with the bats framework.

I'm not sure how much you want the test to cover? Reading the test file (Again, not familiar with bats, so I might be wrong) getting inspiration from the testing of main.cf I suppose a "postfix check" would cover much of it?

**Comment by tomav** [comment]
Yep the same kind we used on main.cf

**Comment by MadsRC** [comment]
@tomav - Added the integration test, and the build succeeds on my local machine when running "make". Seems like the build fails on travis, however, the unit test i made seem to have run fine?

**Comment by tomav** [comment]
Thanks @MadsRC

**Pull request merged**
