### PR TITLE
Also search on the mail so that the email can be dropped

### PR DESCRIPTION
**Pull request by johansmitsnl**
See issue #491

### CODE REVIEW

**Comment by johansmitsnl** [comment]
Any idea why this might fail and what the error is?

**Comment by tomav** [comment]
@johansmitsnl this is still relevant after @alinmear improvements? Thanks.

**Comment by johansmitsnl** [comment]
Need to check it. Hope to do it this weekend.

**Comment by tomav** [comment]
Thank you

**Comment by johansmitsnl** [comment]
Not needed anymore, it is fixed with: #644

**Pull request closed without merging**
