### PR TITLE
Add support for recipient delimiters with aliases fixes #442

### LINKED ISSUE #442: Use recipient_delimiter with aliases
It is currently not possible to use the `recipient_delimiter` (by default +) with aliases configured in `config/postfix-virtual.cf`. The reason is, that dovecot doesn't know about the aliases.

Let's say you have `me@somedomain.com` configured as an account in `config/postfix-accounts.cf` and an alias `full.name@somedomain.com` in `config/postfix-virtual.cf`. When a mail with recipient `full.name+idonttrustyou@somedomain.com` gets received by the mail server, it is processed just fine by postfix. It then tries to deliver the mail to dovecot (as per `virtual_transport` in `target/postfix/main.cf`). Because dovecot is unaware of the aliases it rejects the mail with 
> User doesn't exist: full.name@somedomain.com

### PR DESCRIPTION
**Pull request by nwolber**
I finally got time to add a test case for this. If there is anything that keeps you from merging, please let me know.

### CODE REVIEW

**Comment by nwolber** [comment]
The TravisCI integration seems to be broken. The automatic build got canceled because setting up the containers took more than 20 mins. Is there a way to re-run the tests other than a new commit?

**Comment by tomav** [comment]
Restarted.

**Comment by flole** [comment]
Can it be that this undo the changes made by #305 and #360?

**Comment by tomav** [comment]
@flole, yep it will. - cc @00angus, @tyranron

**Comment by tyranron** [comment]
@tomav @nwolber  
Interesting... I don't think that getting rid of lmtp is best option.  
I'll investigate the issue a lit bit further in few days and will look can be this considered with lmtp or not.

**Comment by tyranron** [comment]
@tomav I've submitted [a PR](https://github.com/tomav/docker-mailserver/pull/528) which adds integration test only provided by @nwolber in this PR. And, as we see, latest `master` passes it.

So, @nwolber, are you sure that this test reproduces your issue?

There is also an [official Dovecot LMTP doc](http://wiki.dovecot.org/LMTP#Address_extension_delivery) which refers us to `lmtp_save_to_detail_mailbox = yes` option. I've tried to enable it, and the only thing is changed that mail is delivered to appropriate folder (specified after delimiter), not to default as happens now.

**Comment by nwolber** [comment]
@tyranron you're totally right. The test only tested the good case. Unfortunately the failure case also produces an e-mail (bounced) with the exact same log message. I added a new step in the test case, that checks for the status=bounced message. I also noticed that the failures seems to occur only if recipient_delimiter is set something other than the standard '+' sign. I also added that to the test case.

I ran the tests both with the lmtp configuration currently present in master and the lda configuration in this PR. The test now fails with lmtp and succeeds with lda.

If there is a solution that gets this working if lmtp I would be more than happy to do that. Unfortunately I don't see how. Any help would be greatly appreciated.

**Comment by tyranron** [comment]
@nwolber thank you for update. I'll dig into and will try to investigate further.

**Comment by tyranron** [comment]
@nwolber I reproduced your test case again in [this PR](https://github.com/tomav/docker-mailserver/pull/528). Just changed `recipient_delimiter` from `-` to `~` to [not collide with other test cases](https://github.com/tomav/docker-mailserver/blob/3d553961d37311ee7b9e60ac808625419817c992/test/email-templates/existing-regexp-alias-external.txt#L6).

The latest master [passes it](https://travis-ci.org/tomav/docker-mailserver/builds/206707386).
The problem was that `recipient_delimiter` was changed in Postfix configuration, but not in Dovecot configuration. This is mentioned in [Dovecot documentation](http://wiki.dovecot.org/LMTP#Address_extension_delivery) I referred earlier.

**Comment by nwolber** [comment]
Yep, you are right. I already had that configuration, but for some other reason it didn't work as expected. I fixed that now and it works. I think this PR can be closed then and #528 should be merged instead. I will also close #442.

Thanks again for your help.

**Pull request closed without merging**
