### PR TITLE
Update command to set container_network

### PR DESCRIPTION
**Pull request by gkobeaga**

### CODE REVIEW

**Comment by johansmitsnl** [comment]
Check #746 and #607 that we want to dump the hardcoded eth0 name.

**Comment by gkobeaga** [comment]
What about setting it as environmental variable? I am using Docker Swarm to deploy it, which uses multiple interfaces. The automatic finding might cause problems.

**Comment by johansmitsnl** [comment]
I see that test `not ok 119 checking PERMIT_DOCKER: my network value` is failing. Could you verify this?

**Comment by erik-wramner** [comment]
Is this still relevant? No changes since January 2018, should we close it or make it work?

**Pull request closed without merging**
