### PR TITLE
Changed max message size

### PR DESCRIPTION
**Pull request by Dschinghis-Kahn**
Added config to increase the maximal message size from 10MB (default) to 40MB.

### CODE REVIEW

**Comment by tomav** [comment]
Hi @Dschinghis-Kahn, why this should go in the default config?

**Comment by Dschinghis-Kahn** [comment]
Hi @tomav, this is a necessary setting if you want to send attachments. For example, with the default you can only send mails with a maximum size of ~7MB (because of base64). That's 2-3 pictures for my camera...
I wonder why there is a size limit on the sending side anyway?! On the receiveing mail server ... okay, but why should one prohibit one self of sending larger mails?
However, this option makes it possible to send larger mails and has no effect when sending small (text only) mails.

**Comment by tomav** [comment]
Hi @Dschinghis-Kahn, thanks for your answer.
Of course I understand the need, but I'm not sure this message size should go in default config and impact all users with default settings.

Do you know that you can set your own settings using [postfix override](https://github.com/tomav/docker-mailserver/wiki/Override-Default-Postfix-Configuration) feature?

**Comment by thiesschneider** [comment]
would be great to have this as env :)

**Comment by Dschinghis-Kahn** [comment]
Overriding with postfix-main.cf worked perfectly. Thanks!

**Pull request closed without merging**
