### PR TITLE
Find the right interface for the container #607

### PR DESCRIPTION
**Pull request by dlion**

### CODE REVIEW

**Comment by johansmitsnl** [comment]
@tomav could you do a rebuild?
@dlion do the tests pass all locally?

**Comment by dlion** [comment]
@johansmitsnl well no, without my edits only 162 tests passed of 167 (5 failed and yes, I inited submodules and updated it, of course, `make` at the end so I don't know why) so I continued to add my changes anyway

**Comment by johansmitsnl** [comment]
I use this command to build and run
`git checkout test/config && make build generate-accounts run generate-accounts-after-run fixtures tests`

**Comment by dlion** [comment]
@johansmitsnl ok using your commands set I obtain only 2 errors, first and after my edits, I don't know why still appear errors

**Comment by johansmitsnl** [comment]
@dlion could you paste the tests that fail.
There are some tests that fail sometimes but they depend on the load on Travis to pass or not.

**Comment by johansmitsnl** [comment]
Don't want to rush you but is there any progress?

**Comment by dlion** [comment]
@johansmitsnl Sorry for my delay, I was very busy in these weeks 😭 
I run your command on the master branch and I obtained 2 errors:

```
✗ checking PERMIT_DOCKER: my network value
   (from function `assert_success' in file test/test_helper/bats-assert/src/asse
rt.bash, line 114,
    in test file test/tests.bats, line 1020)
     `assert_success' failed

   -- command failed --
   status : 1
   output :
   --
```

and

```
✗ checking system: /var/log/mail/mail.log is error free
   (from function `assert_failure' in file test/test_helper/bats-assert/src/asse
rt.bash, line 140,
    in test file test/tests.bats, line 857)
     `assert_failure' failed

   -- command succeeded, but it was expected to fail --
   output : Nov 25 13:07:55 mail postfix/submission/smtpd[2892]: error: open fil
e /32: No such file or directory
   --
```

**Comment by johansmitsnl** [comment]
In #784 we switched to debian. You should rebase on master.

**Comment by erik-wramner** [comment]
I'll close this as outdated. Please protest if it is still valid and describe what problem it solves.

**Pull request closed without merging**
