### PR TITLE
Added optional file user-patches.sh for own patches without recompiling

### PR DESCRIPTION
**Pull request by vortex852456**
As @erik-wramner suggested in https://github.com/tomav/docker-mailserver/issues/1281 I created this pull request.

Sadly I wasn't able to test with the current tip of master. Error while starting:
`2019-10-07 20:45:23,793 INFO spawned: 'mailserver' with pid 8`
`supervisor: couldn't exec /usr/local/bin/start-mailserver.sh: ENOENT`
`supervisor: child process was not spawned`

This is my first pull request. Feel free to inform me whenever I was doing domething wrong.

### CODE REVIEW

**Comment by Undercover1989** [comment]
The error does not seem to have anything to do with the changes I made. See https://github.com/tomav/docker-mailserver/issues/1285

**Comment by erik-wramner** [comment]
I'm afraid that the error is caused by your change. I triggered a rebuild and got the same failure, but master builds. You should be able to run the tests locally if you have a Linux box (the tests don't work with Windows or Mac), see https://github.com/tomav/docker-mailserver/blob/master/CONTRIBUTING.md. In particular you need to init the submodules.

**Comment by Undercover1989** [comment]
I've problems fixing this. When I start my self build mailserver, I get following unusal output from log:
`/tmp/docker-mailserver /`
`/`
`Starting Misc`
`user-patches hello world!` (this is an echo from my testing user-patches.sh)
`Error: Please fix your configuration. Exiting...`

When I comment out the line `/tmp/docker-mailserver/user-patches.sh` the server boots as expected. I dont't get it.

**Comment by Undercover1989** [comment]
Now I'm totally confused. I've added `DMS_DEBUG=1` to my environment. With this the mailserver boots up...

`  Setting up configuration checksum file,`
`/tmp/docker-mailserver /,`
`  * Creating /tmp/docker-mailserver-config-chksum,`
`/,`
`  Checking /var/mail permissions,`
`  * Permissions in /var/mail look OK,`
`  Checking $amavis_state_dir permissions,`
`  * Permissions in /var/lib/amavis look OK,`
`  Cleaning up disabled Clamav,`
`  Cleaning up disabled spamassassin,`
`Starting Misc,`
`  * Executing user-patches.sh,`
`user-patches hello world!,`
`  * user-patches.sh executed,`
`Starting mail server`

**Comment by erik-wramner** [comment]
I'll look into it when I get some free time. The CI tests still fail on the fixtures though, so something must be seriously wrong.

**Comment by Undercover1989** [comment]
I've tested `make build-no-cache generate-accounts run generate-accounts-after-run fixtures tests clean` with commit https://github.com/tomav/docker-mailserver/pull/1284/commits/275a83667a76fef1046fa3306a09f72aa4686352 and it was successful on my machine (debian-buster). But the Travis CI build is still failing.

**Comment by vortex852456** [comment]
Great! I'm taking care of it this or next weekend. Thanks for your effort!

**Comment by erik-wramner** [comment]
Looks good so far, I'll wait for the test before merging. Have a nice weekend!

**Comment by vortex852456** [comment]
Hope you had two nice weekends. Sorry for the delay.

Can I add the new test to https://github.com/tomav/docker-mailserver/blob/master/test/tests.bats ? Or where would you place it?

I must admit that implementing the test is a not so easy step for me. Have to learn and understand how it works before I can start. If you could give me some coarse instructions it may help me a lot on getting this implemented faster.

**Comment by erik-wramner** [comment]
Well, either in test.bats or in one of the new mail_something.bats. We are trying to break up the tests to avoid having to start all the  docker images up front.

In your case you could use test.bats and add a new function in the "configuration checks" section. Make sure that an example script is mounted into one of the containers (for example mail) in the `Makefile` but not into all containers. Then add a new test, something like (pseudo code):
```

@test "checking configuration: user-patches.sh executed" {
  run docker logs mail | grep expected_output_from_user_patches
  assert_output "expected output..."
}

```

**Comment by vortex852456** [comment]
Argh, the new test doesn't pass. I guess I have to set up an local IDE to examine this further. You will hear from me :-) Thanks so far!

**Comment by vortex852456** [comment]
image

**Comment by sebka** [comment]
@erik-wramner pls have a look @ the new test.
i would really like to know why bats could not match those two strings.

**Comment by erik-wramner** [comment]
Hm, strange. @fbartels do you have any idea?

At least I merged the PR. Thanks for taking the time!

**Comment by fbartels** [comment]
Hmm, the only thing I could think of are trailing spaces.

**Pull request merged**
