### PR TITLE
Implement undef option for SA_SPAM_SUBJECT

### PR DESCRIPTION
**Pull request by elbracht**
Use `undef` to disable the sa_spam_subject_tag in amavis config. Currently the string "undef" is written before the email subject.

### CODE REVIEW

**Comment by johansmitsnl** [comment]
You also could add a empty string if you don't want the tag?

**Comment by elbracht** [comment]
I think the script use the default value for empty strings.

```
SA_SPAM_SUBJECT=${SA_SPAM_SUBJECT:="***SPAM*** "} && ...
```

**Comment by johansmitsnl** [comment]
Correct, could you add a test to this PR to verify that it works?

**Comment by elbracht** [comment]
Is there any other way than create a new docker container in `Makefile` to test this case? I think it's overkill for this test.

**Comment by johansmitsnl** [comment]
This variable is already tested in:
https://github.com/tomav/docker-mailserver/blob/0748734b198ddbe9a67e7589bf73c4b011e4983a/Makefile#L21-L37

I guess adding a new container is the best way to test this.

**Comment by elbracht** [comment]
I think the failed tests are not my fault

**Pull request merged**
