### PR TITLE
Added smtpd_sender_login_maps

### PR DESCRIPTION
**Pull request by TechnicLab**
Added smtpd_sender_login_maps for reject_sender_login_mismatch postfix option.

### CODE REVIEW

**Comment by johansmitsnl** [comment]
This file does not needs to be only set when using ldap?

**Comment by TechnicLab** [comment]
Totally forgot about it - yes, this modification is for ldap. Not sure where to find file with those contents without ldap:
"The controlled_envelope_senders table specifies the binding between a sender envelope address and the SASL login names that own that address:

/etc/postfix/controlled_envelope_senders
    # envelope sender           owners (SASL login names)
    john@example.com            john@example.com
    helpdesk@example.com        john@example.com, mary@example.com
    postmaster                  admin@example.com
    @example.net                barney, fred, john@example.com, mary@example.com
"

**Comment by johansmitsnl** [comment]
So this can be merged or are changes still needed?

**Comment by TechnicLab** [comment]
Now it works in my ldap setup. Waiting for tests.

**Comment by 17Halbe** [comment]
Can you please check if this would work with ldap as well. Otherwise we would have to differentiate between ldap and non ldap builds.

Please see the comments.

**Comment by TechnicLab** [comment]
A am a beet confused. You would like me to check your solution from comment in another pull request? I will test it when I will be near PC.

**Comment by TechnicLab** [comment]
A am a beet confused. You would like me to check your solution from comment in another pull request? I will test it when I will be near PC.

**Comment by 17Halbe** [comment]
Sorry for the confusion.. 
Yes, exactly! That would be great.
Your PR is only working for ldap users. So in case we would implement smtpd_sender_login_maps for everyone else as well, we would have to distinguish upon server start, which mapping file we need to use.
(Depending if that's a ldap or a "standard" setup) 
So, if the regex suggestion works for you/ldap as well, than we just need this one mapping file for everyone.

I hope this was less confusing!

**Comment by johansmitsnl** [comment]
@TechnicLab could you fix the conflict?

**Comment by johansmitsnl** [comment]
Almost all tests fail, looks like a typo somewhere?

**Comment by TechnicLab** [comment]
Actually there was no confusion anymore, it was too late in my time zone. Unfortunately stilll no near PC(

**Comment by TechnicLab** [comment]
Unfortunately it is not working with my ldap setup. I guess we need to separate ldap and simple configurations.

**Comment by johansmitsnl** [comment]
I personally use ldap but I don't encounter any issues at the moment with master. Does this mean the restriction is not working?

ps. I have extracted the ldap service in this project in it own docker: https://hub.docker.com/r/jsmitsnl/docker-openldap-postfix-book

**Comment by TechnicLab** [comment]
I manually added changes from 17Halbe and they lead to inability to send any mail. In current master you can still send messages from any email.

**Comment by johansmitsnl** [comment]
Ok, why do the tests for this PR fail do you know why?

**Comment by TechnicLab** [comment]
Actually I have no idea.

**Comment by 17Halbe** [comment]
Ok thanks for trying.. Shouldn't this be the default(not letting every signed in user spoof its address)?

**Comment by TechnicLab** [comment]
No, this is not the default behavior.

**Comment by 17Halbe** [comment]
I know, but IMHO it should be! 
\So it has to be implemented for everyone else as well!

**Comment by TechnicLab** [comment]
I absolutely agree with you, but maybe there is a reason for such default configuration?

**Comment by 17Halbe** [comment]
I'll provide a PR on this in a few days. Should be easy enough.

**Comment by TechnicLab** [comment]
warning: pcre map /etc/postfix/sender.cf, line 1: no closing regexp delimiter "+": ignoring this rule. It looks like there is an error with your regexp.

**Comment by 17Halbe** [comment]
You copied the + from the comment as well.. Which is actually great, since this leaves a silverlining, that it will still probably work.
Just remove the leading + from the expression! Does it work?

**Comment by TechnicLab** [comment]
Great! It working now.

**Comment by TechnicLab** [comment]
Well, this pull request can be merged when we will determine why it is causing tests failitures.

**Comment by 17Halbe** [comment]
Can you add a testcase for a user spoofing it's address?

**Comment by TechnicLab** [comment]
I am making changes mainly online on GitHub without cloning repo, so I can’t check whatever test work locally or not. I will look into projects’s tests closer and will try to create spoofing test.

**Comment by 17Halbe** [comment]
Did you check, if you could still receive mail from a foreign address? I think this is actually be blocking anyone sending mails to the server.
If that's the case(which I am pretty sure of), try replacing reject_sender_login_mismatch  with `reject_authenticated_sender_login_mismatch`

**Comment by TechnicLab** [comment]
Looks like you are right, my test container rejects mail from foreign addresses.

**Comment by 17Halbe** [comment]
and reject_authenticated_sender_login_mismatch? Does that work as expected?

**Comment by TechnicLab** [comment]
Yes

**Comment by 17Halbe** [comment]
/etc/postfix/senders.cf: No such file or directory
Modify the Dockerfile to copy that file over to the container

**Comment by TechnicLab** [comment]
Thats's strange: ldap tests failed but it works locally.

**Comment by johansmitsnl** [comment]
@TechnicLab Could you fix the conflict and update the branch for a retest?

**Comment by TechnicLab** [comment]
Well, it should work now. I will add tests today.

**Comment by johansmitsnl** [comment]
@TechnicLab love to merge the PR, could you inform me about the state of adding tests?

**Comment by TechnicLab** [comment]
I’m sorry, I am currently ill and was not in great working condition.

**Comment by johansmitsnl** [comment]
@TechnicLab hope you get well soon

**Comment by 17Halbe** [comment]
@TechnicLab  I hope you don't consider this being rude, I just needed some distraction from work and for a change wanted to contribute to something useful! :wink: 
So I continued your work and provided a PR here: #872

**Comment by 17Halbe** [comment]
Since #872 has been merged, this can be closed, right?

**Comment by erik-wramner** [comment]
Closing due to no response, probably fixed by #872.

**Pull request closed without merging**
