### PR TITLE
Expand the decoders for amavis

### PR DESCRIPTION
**Pull request by johansmitsnl**
See #659

### CODE REVIEW

**Comment by Fmstrat** [comment]
All of these aren't required, I would suggest trimming back. For instance, zip has an internal decoder, so there isn't a need to add "zip" as a package. The only decoders missing are:

```
mail                 | Jul 20 15:38:51 mail amavis[1590]: No decoder for       .F
mail                 | Jul 20 15:38:51 mail amavis[1590]: No decoder for       .arc
mail                 | Jul 20 15:38:51 mail amavis[1590]: No decoder for       .cab
mail                 | Jul 20 15:38:51 mail amavis[1590]: No decoder for       .deb
mail                 | Jul 20 15:38:51 mail amavis[1590]: No decoder for       .doc
mail                 | Jul 20 15:38:51 mail amavis[1590]: No decoder for       .iso
mail                 | Jul 20 15:38:51 mail amavis[1590]: No decoder for       .jar
mail                 | Jul 20 15:38:51 mail amavis[1590]: No decoder for       .lha
mail                 | Jul 20 15:38:51 mail amavis[1590]: No decoder for       .lrz
mail                 | Jul 20 15:38:51 mail amavis[1590]: No decoder for       .lz4
mail                 | Jul 20 15:38:51 mail amavis[1590]: No decoder for       .lzma
mail                 | Jul 20 15:38:51 mail amavis[1590]: No decoder for       .lzo
mail                 | Jul 20 15:38:51 mail amavis[1590]: No decoder for       .rar
mail                 | Jul 20 15:38:51 mail amavis[1590]: No decoder for       .rpm
mail                 | Jul 20 15:38:51 mail amavis[1590]: No decoder for       .swf
mail                 | Jul 20 15:38:51 mail amavis[1590]: No decoder for       .xz
mail                 | Jul 20 15:38:51 mail amavis[1590]: No decoder for       .zoo
```

**Comment by johansmitsnl** [comment]
@Fmstrat I removed the zip, others are needed for the missing decoder list.

**Comment by Fmstrat** [comment]
Looks good to me! Hopefully we get a merge on this soon.

**Comment by johansmitsnl** [comment]
@tomav @alinmear I have updated the PR with tests and they pass all now. 
Can someone review and accept if ok?

**Comment by gutmensch** [comment]
Well done, @johansmitsnl! I would also like to see this merged soon.

**Comment by tomav** [comment]
Thanks @johansmitsnl

**Pull request merged**
