### PR TITLE
Ensure that the account contains a @

### LINKED ISSUE #923: Adding emails without domains fails
## Context

When trying to configure the server, the docker container started but no process were running. When checking the logs with docker logs, I spotted this:

```
#
#
# docker-mailserver
#
#

Initializing setup
Checking configuration
Configuring mail server
Error: Unless using LDAP, you need at least 1 email account to start the server.
Error: Please fix your configuration. Exiting...
```
I was sure that I ran the setup.sh as described, so I checked the addmailuser script, and I realized that it expected an account in the form "user@domain", while I just provided "user" after reading the README file.

## Expected Behavior

The creation of an email account without a proper domain should be rejected with an error message.

## Actual Behavior

The creation succeeded, then the container start but without any service running.

## Possible Fix

PR incoming :-)

## Steps to Reproduce

1 Follow the README, but omit to add the domain when creating an account:
 ./setup.sh email add foobar password
2. docker-compose -d up mail

### PR DESCRIPTION
**Pull request by piwai**
Fixes #923

### CODE REVIEW

**Comment by johansmitsnl** [comment]
Could you add a test for this change?

**Comment by piwai** [comment]
@johansmitsnl Done :-)

**Comment by piwai** [comment]
Hmm, there are failures but apparently unrelated to the test I added :/

**Comment by johansmitsnl** [comment]
restarted the test build

**Comment by johansmitsnl** [comment]
@piwai Same test 130 failed. This might be related to the setup change you made. Could you verify this test?

**Comment by johansmitsnl** [comment]
@piwai in #934 also fails and saw that the test was also failing earlier.

Do you have any idea why?

**Pull request merged**
