### PR TITLE
Introducing Postscreen

### LINKED ISSUE #718: Proxy protocol support
Hi, Just a question.

I deployed this docker-mailserver image on kubernetes behind haproxy which sends proxy-protocol.
But seems amavis failed to send email to smtpd.
Please see following log messages.

> Sep  7 05:53:59 mailserver postfix/smtpd[1062]: warning: haproxy read: unexpected EOF

I guess [127.0.0.1:10025](https://github.com/tomav/docker-mailserver/blob/master/target/postfix/master.cf#L101) expect to receive proxy protocol but amavis  didn't send.
I think I should modify `master.cf` file before launching.

So Is there any official way to configure `master.cf` file after docker-mailserver is deployed?

Thanks.

### Full Log

```
Sep  7 05:53:20 mailserver postfix/smtpd[1053]: connect from st41p57im-ztfb14240501.us.com[17.36.64.138]
Sep  7 05:53:21 mailserver postfix/smtpd[1053]: C991582EA6D697E4B6C12: client=st41p57im-ztfb14240501.us.com[17.36.64.138]
Sep  7 05:53:22 mailserver postfix/cleanup[1058]: C991582EA6D697E4B6C12: message-id=<DCEE9524-F30F-4439-B242-0092ED176612@us.com>
Sep  7 05:53:22 mailserver opendkim[184]: C991582EA6D697E4B6C12: st41p57im-ztfb14240501.us.com [17.36.64.138] not internal
Sep  7 05:53:22 mailserver opendkim[184]: C991582EA6D697E4B6C12: not authenticated
Sep  7 05:53:22 mailserver opendkim[184]: C991582EA6D697E4B6C12: DKIM verification successful
Sep  7 05:53:22 mailserver opendkim[184]: C991582EA6D697E4B6C12: s=04042017 d=us.com SSL
Sep  7 05:53:22 mailserver opendmarc[196]: implicit authentication service: mail.lazy.work
Sep  7 05:53:22 mailserver opendmarc[196]: C991582EA6D697E4B6C12: us.com pass
Sep  7 05:53:22 mailserver postfix/qmgr[1033]: C991582EA6D697E4B6C12: from=<user01@us.com>, size=2180, nrcpt=1 (queue active)
Sep  7 05:53:23 mailserver postfix/smtpd[1053]: disconnect from st41p57im-ztfb14240501.us.com[17.36.64.138] ehlo=2 starttls=1 mail=1 rcpt=1 data=1 quit=1 commands=7
Sep  7 05:53:59 mailserver amavis[1045]: (01045-01) (!)rw_loop: leaving rw loop, no progress, last event (select) 35.011 s ago
Sep  7 05:53:59 mailserver postfix/smtpd[1062]: warning: haproxy read: unexpected EOF
Sep  7 05:53:59 mailserver postfix/smtpd[1062]: connect from unknown[unknown]
Sep  7 05:53:59 mailserver postfix/smtpd[1062]: disconnect from unknown[unknown] commands=0/0
Sep  7 05:53:59 mailserver amavis[1045]: (01045-01) (!)O440fHx7_I21 FWD from <user01@us.com> -> <user02@lazy.work>,  451 4.5.0 From MTA() during fwd-connect (No greeting, dt: 35.012 s): id=01045-01
Sep  7 05:53:59 mailserver amavis[1045]: (01045-01) Blocked MTA-BLOCKED {TempFailedInbound}, [17.36.64.138]:36637 [17.36.64.138] <user01@us.com> -> <user02@lazy.work>, Queue-ID: C991582EA6D697E4B6C12, Message-ID: <DCEE9524-F30F-4439-B242-0092ED176612@us.com>, mail_id: O440fHx7_I21, Hits: -0.322, size: 2367, dkim_sd=04042017:us.com, 37021 ms
Sep  7 05:53:59 mailserver postfix/smtp[1034]: C991582EA6D697E4B6C12: to=<user02@lazy.work>, relay=127.0.0.1[127.0.0.1]:10024, delay=39, delays=1.6/0.01/0.01/37, dsn=4.5.0, status=deferred (host 127.0.0.1[127.0.0.1] said: 451 4.5.0 id=01045-01 - Temporary MTA failure on relaying, From MTA() during fwd-connect (No greeting, dt: 35.012 s): id=01045-01 (in reply to end of DATA command))
```

### ConfigMap I used

* https://github.com/yuanying/k8s-env/blob/master/charts/mailserver/templates/configmaps.yaml#L23-L35

### LINKED ISSUE #780: Introduce postscreen?!
Hi there,
what about postscreen? I had it running for quite some time and at least the use of blacklists from different providers repelled almost all attacks on my server. I had around 1 a week. With this server I get several a day.
I would be able to work on a PR next year. 34C3 First! ;)
Anyone interested?

For those who don't know postscreen:
Some more info from the [Postscreen readme](http://www.postfix.org/POSTSCREEN_README.html):

>  Most email is spam, and most spam is sent out by zombies (malware on compromised end-user computers). Wietse expects that the zombie problem will get worse before things improve, if ever. Without a tool like postscreen(8) that keeps the zombies away, Postfix would be spending most of its resources not receiving email.
>The main challenge for postscreen(8) is to make an is-a-zombie decision based on a single measurement. This is necessary because many zombies try to fly under the radar and avoid spamming the same site repeatedly. Once postscreen(8) decides that a client is not-a-zombie, it whitelists the client temporarily to avoid further delays for legitimate mail.
Zombies have challenges too: they have only a limited amount of time to deliver spam before their IP address becomes blacklisted. To speed up spam deliveries, zombies make compromises in their SMTP protocol implementation. For example, they speak before their turn, or they ignore responses from SMTP servers and continue sending mail even when the server tells them to go away.
postscreen(8) uses a variety of measurements to recognize zombies. First, postscreen(8) determines if the remote SMTP client IP address is blacklisted. Second, postscreen(8) looks for protocol compromises that are made to speed up delivery. These are good indicators for making is-a-zombie decisions based on single measurements.
postscreen(8) does not inspect message content. Message content can vary from one delivery to the next, especially with clients that (also) send legitimate email. Content is not a good indicator for making is-a-zombie decisions based on single measurements, and that is the problem that postscreen(8) is focused on. 

-   As the first layer, postscreen(8) blocks connections from zombies and other spambots that are responsible for about 90% of all spam. It is implemented as a single process to make this defense as inexpensive as possible.
-  The second layer implements more complex SMTP-level access checks with Postfix SMTP servers, policy daemons, and Milter applications.
- The third layer performs light-weight content inspection with the Postfix built-in header_checks and body_checks. This can block unacceptable attachments such as executable programs, and worms or viruses with easy-to-recognize signatures.
- The fourth layer provides heavy-weight content inspection with external content filters. Typical examples are Amavisd-new, SpamAssassin, and Milter applications.

CU,

    Alex

### PR DESCRIPTION
**Pull request by 17Halbe**
Cheaper, earlier and simpler blocking of zombies/spambots.

From http://postfix.cs.utah.edu/POSTSCREEN_README.html :
As a first layer, postscreen(8) blocks connections from zombies and other spambots that are responsible for about 90% of all spam. It is implemented as a single process to make this defense as cheap as possible.

Things we need to consider:

 - Do we need a whitelist/backlist file? (http://postfix.cs.utah.edu/postconf.5.html#postscreen_access_list)
   - Via introducing an optional config/postfix-access.cidr
   - The only permanent whitelisting I could imagine are monitoring services(which might (still?) behave weird/hastely) or blacklisting backup servers(since no traffic should be coming from them anyway)
 - Do we need deep inspections? They are desireable, but these tests are expensive: a good client must disconnect after it passes the test, before it can talk to a real Postfix SMTP server. Considered tests are:
   - postscreen_bare_newline_enable (http://postfix.cs.utah.edu/postconf.5.html#postscreen_bare_newline_action)
   - postscreen_non_smtp_command_enable (http://postfix.cs.utah.edu/postconf.5.html#postscreen_non_smtp_command_action)
   - postscreen_pipelining_enable (http://postfix.cs.utah.edu/postconf.5.html#postscreen_pipelining_action)
- Do we need to make the blacklisting via dnsblocking configurable? It's currently set and weighted as follows, where a score of 3 results in blocking, a score of -1 results in whitelisting:
   (*: adds the specified weight to the SMTP client's DNSBL score. Specify a negative number for whitelisting.)
   (http://postfix.cs.utah.edu/postconf.5.html#postscreen_dnsbl_sites)
   - zen.spamhaus.org*3
   - bl.mailspike.net
   - b.barracudacentral.org*2
   - bl.spameatingmonkey.net
   - bl.spamcop.net
   - dnsbl.sorbs.net
   - psbl.surriel.com
   - list.dnswl.org=127.0.[0..255].0*-2
   - list.dnswl.org=127.0.[0..255].1*-3
   - list.dnswl.org=127.0.[0..255].[2..3]*-4
- What to do when blacklisting? I currently set it to drop. We could
   - ignore: Ignore the failure of this test. Allow other tests to complete. Repeat this test the next time the client connects. This option is useful for testing and collecting statistics without blocking mail.
   - enforce: Allow other tests to complete. Reject attempts to deliver mail with a 550 SMTP reply, and log the helo/sender/recipient information. Repeat this test the next time the client connects.
   - drop: Drop the connection immediately with a 521 SMTP reply. Repeat this test the next time the client connects.

In the end I think we could drop postgrey support. Postscreen replaces postgrey in its entirety, while being more selective and not delaying mail. Especially if we consider using the deep inspection options of postscreen.

Hope that wasn't too much to read! ;) 
This closes #780 and closes #718

### CODE REVIEW

**Comment by johansmitsnl** [comment]
Build is failing very early, did tests pass on your pc?

**Comment by 17Halbe** [comment]
This should work now.. I guess I tested the master branch m)
The fail2ban test is failing, since postscreen is dropping the connection early.
We dump the  Auth request into postfix via nc, which is not waiting for its turn to speak and therefore gets correctly banned by postscreen:
`Jan 28 22:34:15 mail postfix/postscreen[3421]: CONNECT from [172.17.0.17]:53116 to [172.17.0.8]:25
Jan 28 22:34:15 mail postfix/postscreen[3421]: PREGREET 80 after 0 from [172.17.0.17]:53116: EHLO mail\nAUTH LOGIN dXNlcjFAbG9jYWxob3N0LmxvY2FsZG9tYWlu\nBn3JKisq4HQ2RO==\nQUIT\n
Jan 28 22:34:15 mail postfix/postscreen[3421]: DISCONNECT [172.17.0.17]:53116
Jan 28 22:34:15 mail postfix/postscreen[3421]: CONNECT from [172.17.0.17]:53118 to [172.17.0.8]:25
Jan 28 22:34:15 mail postfix/postscreen[3421]: PREGREET 80 after 0 from [172.17.0.17]:53118: EHLO mail\nAUTH LOGIN dXNlcjFAbG9jYWxob3N0LmxvY2FsZG9tYWlu\nBn3JKisq4HQ2RO==\nQUIT\n
Jan 28 22:34:15 mail postfix/postscreen[3421]: DISCONNECT [172.17.0.17]:53118`

So no failed Auth request is ever logged.

I guess I have to rewrite the test.. Which is going to be much more painfull! ;)

**Comment by 17Halbe** [comment]
I think the only reasonable setting for the user to choose from would be the action option:
- **ignore**: Ignore the failure of this test. Allow other tests to complete. Repeat this test the next time the client connects. This option is useful for testing and collecting statistics without blocking mail.
- **enforce**: Allow other tests to complete. Reject attempts to deliver mail with a 550 SMTP reply, and log the helo/sender/recipient information. Repeat this test the next time the client connects.
- **drop**: Drop the connection immediately with a 521 SMTP reply. Repeat this test the next time the client connects.
What do you think, do we need a variable for that?

**Comment by 17Halbe** [comment]
Added:

- tests
- new config option POSTSCREEN_ACTION (default enforce)
- added links to Intro in README.md
- added documentation to README.md
- repaired Fail2Ban testcase

**Please note: This build will never pass the integration tests. The test-case for Fail2Ban was wrong and has been corrected.**

**Comment by johansmitsnl** [comment]
@17Halbe Very good work!

**Pull request merged**
