### PR TITLE
Complete refactoring for `start-mailserver.sh`

### PR DESCRIPTION
**Pull request by aendeavor**
# The Second Half

This one is rather a blue whale. I completely refactored `start-mailserver.sh`. Therefore, it is now included into `shellcheck`. This was indeed a slow decend into madness.

## Changes

- completely refactored `start-mailserver.sh`
- adjusted Makefile to check this script too

## To Do

- [x] close #1550
- [x] get rid of as many `#shellcheck disable...` comments as possible
- [x] correct the `Makefile` to use `/usr/bin/shellcheck`

## Post Scriptum

@erik-wramner I accidentally merge-commited all commits from #1601; I will squash them next time. I'm sorry for the inconvenience.

### CODE REVIEW

**Comment by erik-wramner** [comment]
I have this on my TODO list, I'll try to find time in the weekend.

**Comment by aendeavor** [comment]
any news on your side @erik-wramner ? @fbartels have you had time?

**Review by fbartels — APPROVED** [review]
Sorry, quite a large changeset and therefore not that easy to review. But in the end it looks like almost exclusively formatting changes and no functional changes (at least I cannot remember seeing one of those).

**Comment by aendeavor** [comment]
That's correct @fbartels. In the end, it's only a refactoring:) The only "major" changes are those where I substituted code, for example

``` BASH
array=$(cat $THIS | tr ":" "\n"
```

which is ugly and not robust became 

``` BASH
declare -a ARRAY
IFS=':'
read -r -a ARRAY < <(cat "${THIS}")
```

which is more verbose, but `read` was made for exactly this case, therefore being robust.

There were similar changes here and there. The majority of line changes came from brace substitutions and `""` around variables.

**Comment by aendeavor** [comment]
@erik-wramner I see you have very little time at hand, plus the PR is pretty big. I really understand this and I don't want to force you into reviewing these changes. If it's okay with you, just tell me: @fbartels already approved and the test look good, so there should be no risk involved in merging this if you are okay with not having review this one. What's your take on this?

**Review by erik-wramner — APPROVED** [review]

**Comment by erik-wramner** [comment]
I've approved the changes. I'll try to make a release this weekend provided that master is stable (i.e. no serious bugs reported).

**Pull request merged**
