### PR TITLE
Fix ldap related critical Problems

### PR DESCRIPTION
**Pull request by alinmear**
As already written by me (https://github.com/tomav/docker-mailserver/issues/641#issuecomment-312585289) we have some serious issues regarding the setup of ldap with env variables. 

This pr should fix the following issues: #641, #633, #491 (see comments), #636 (can be configured explicit with the new env vars; maybe we should discuss better defaults as stated there), #591 

* `LDAP_QUERY_FILTER_USER`
* `LDAP_QUERY_FILTER_GROUP`
* `LDAP_QUERY_FILTER_ALIAS`
* `DOVECOT_USER_FILTER`
* `DOVECOT_PASS_FILTER`

We may should discuss some defaults and or combinations to make the setup more straight forward (like dovecot user_filter and pass_filter could be the same, when only 1 has been defined or LDAP_QUERY_FILTER_USER could be set for the saslauthd part if not explicitly set).

Hope this helps ...

### CODE REVIEW

**Comment by tomav** [comment]
Thanks @alinmear

**Comment by Joshua-Ashton** [comment]
Thanks for this, I will try it out if I get a chance later this week

**Comment by tailtwo** [comment]
Thank you, I really didn't have the time to check the source to fix #591 so this mr will come in handy.

**Comment by johansmitsnl** [comment]
The new variable don't work because they are in comment. Why is this?
Now the dovecot variable don't work, so did not build a new image to test.

https://github.com/tomav/docker-mailserver/blob/21fb3f3c86391f079afb7fb59260b64019fa2e51/target/start-mailserver.sh#L593:L595

**Comment by alinmear** [comment]
@johansmitsnl, these are only default values. If you want to change those values you need to set the corresponding ENV Variables, like:

```
- DOVECOT_PASS_FILTER="(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%n))"
- DOVECOT_USER_FILTER="(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%n))"
```

I already wrote an example within the readme.

**Comment by johansmitsnl** [comment]
Inside the docker:
```
echo $DOVECOT_PASS_FILTER
(&(objectClass=PostfixBookMailAccount)(|(uniqueIdentifier=%n)(mail=%u)))
```

```
cat /etc/dovecot/dovecot-ldap.conf.ext
pass_attrs          = uniqueIdentifier=user,userPassword=password
pass_filter         = (&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%n))
user_attrs          = mailHomeDirectory=home,mailUidNumber=uid,mailGidNumber=gid,mailStorageDirectory=mail
user_filter         = (&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%n))
```

It seems that the variables are not applied but they are set in the ENV.

**Comment by alinmear** [comment]
@johansmitsnl , the problem here is the `|` within your expression; because we take the `|` for the separation of the sed parts; this is causing the problem; you could escape the `|` like:

```bash
(&(objectClass=PostfixBookMailAccount)(\|(uniqueIdentifier=%n)(mail=%u)))
```

This should work. I check how to deal with this kind of characters and sed

**Comment by johansmitsnl** [comment]
@alinmear Escaping worked and solved my ldap issue #636.
It should only escape the special chars as you already noted.

Now we only have the #642 to rework to support virtual domains in the ldap. Will take a look how the changes where made and update the PR.

**Pull request merged**
