### PR TITLE
Usermanagement

### PR DESCRIPTION
**Pull request by Crafter6432**
This would make the process of adding a users a bit more convenient, but requires the config volume to be mounted. 

Adds the following commands:
```
 addmailuser <user@domain> [password]
 delmailuser <user@domain>
```

### CODE REVIEW

**Comment by tomav** [comment]
@Crafter6432 Could you add integration tests to be sure that everything works as expected?

**Comment by Crafter6432** [comment]
Seems like the imap STARTTLS is failing from time to time, cloud you rerun the tests ?

**Comment by Crafter6432** [comment]
The said test even fails on master, I guess the dovecot package was updated in ubuntu's repo ?

Tests on master:
https://gist.github.com/Crafter6432/a42c3b5b4cf88a95abd67aed145e60ec

**Comment by tomav** [comment]
Just restarted the build. Sometimes this on fails, probably when container is not 100% started.

**Comment by tomav** [comment]
Better now.

**Comment by tomav** [comment]
Merged.

@Crafter6432 could add some notes in https://github.com/tomav/docker-mailserver/wiki/Configure-Accounts ?

Thank you.

**Pull request merged**
