### PR TITLE
New option DOVECOT_MAILBOX_FORMAT

### PR DESCRIPTION
**Pull request by gmasse**
Add a new option `DOVECOT_MAILBOX_FORMAT`to set Dovecot `mail_location` accordingly.
Issue #1313

### CODE REVIEW

**Comment by erik-wramner** [comment]
Looks good, two very minor things. One is the indentation for the case/esac block in the start script. I guess it mixes tabs and spaces because the code doesn't line up. Not a big deal but easy to fix.

The other is the readme. Perhaps you could add a note that the two new formats were added to docker-mailserver in November 2019 and should be considered experimental until they have been tested in the wild for a while? I don't expect problems, but one never knows and then at least prospective new users have been warned.

**Comment by gmasse** [comment]
I agree @erik-wramner, I will fix and add the comment.
Why not creating a `Testing` branch? `Master` would continue to be fed with bugfixes and minor changes when `Testing` would integrate big changes and enhancements. My 2 cents ;)

**Comment by erik-wramner** [comment]
We could do that, but most of the work consists of fixes that everyone should get and then `latest` followed by `stable` works well. The next big thing is the upgrade to buster and there is a separate branch for that.

**Comment by gmasse** [comment]
Grr I am fighting to correctly push my updates...

**Comment by erik-wramner** [comment]
Are you done, or still fighting?

**Comment by gmasse** [comment]
PR is good now.
Test has failed; I suspect a race condition or something like that. I cannot easily identify the root cause.
@erik-wramner can you relaunch the build?

**Comment by erik-wramner** [comment]
Restarted. That error is not one of the frequent ones, but I have seen it before. Let's see what happens!

**Comment by erik-wramner** [comment]
It worked, I merged the changes. Thanks!

**Pull request merged**
