### PR TITLE
Solve Fetchmail imap idle issue

### PR DESCRIPTION
**Pull request by brainkiller**
Initial pull request to implement the functionality requested in #1728 
Only a few smoke tests have been done so far.

I'm not sure if the fetchmail idfile can be share across all separate fetchmail instances. If needed/preferred we can split this also.

### CODE REVIEW

**Comment by brainkiller** [comment]
Do you accept perl scripting in the repo or should I rewrite the fetchmailrc_split script to bash ?
Probably it will be a bit more cumbersome to achieve the same goal but maybe you prefer it to make it easier to maintain the script.

**Comment by brainkiller** [comment]
I've proposed a change to resolve the shellcheck issues but keeping the perl script

**Review by aendeavor — CHANGES_REQUESTED** [review]
Due to holidays the reviews and comments might take some time:) First of all: Thanks for your PR! It looks fine to me.

You already asked the question I was about to ask: Perl or Bash? While I do not see any issues with the Perl code, I cannot maintain it since I do not write Perl. I think this might be an issue to other maintainers as well. Therefore, I would like to see this code re-written in Bash. I'm sorry for this late response, but this will keep things in line.

**Comment by brainkiller** [comment]
Hi aendeavor,

Thanks for the feedback, I added a bash version of the script and the checks are currently running.
Feel free to chose if you go with the perl or bash version. 

I'll wait for the feedback of the other reviewers before making further changes

**Comment by erik-wramner** [comment]
I think the code looks fine except that there are no tests.

**Comment by brainkiller** [comment]
It looks like the tests failed because if the docker rate limitations :(
`# toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit`

**Comment by aendeavor** [comment]
> It looks like the tests failed because if the docker rate limitations :(
> 
> `# toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit`

Every 6 hours 100 pulls from hub.docker.io - I thought this was enough. I think if we wait a bit this issue resolved itself.

For the tests: yes, there are some tests to be done:)

**Comment by brainkiller** [comment]
Ant idea how i can relaunch the tests ?

**Comment by aendeavor** [comment]
@brainkiller We are currently migrating the repository since the situation with the tests and TravisCI had become hopeless. Therefore, when docker-mailserver/docker-mailserver#6 is merged, I will close this PR and you'll just need to re-open over there. The tests there are improved and run very well. We will just need a little bit more time. I will notice everyone with open PRs, be assured.

**Comment by aendeavor** [comment]
Funnily enough, the PR was just merged. Please re-open with your changes based on the currently latest master. You will encounter some differences with the new master branch, namely:

1. Your description for the env variable will no go in a separate file called `ENVIRONEMNT.md`
2. `start-mailserver.sh` was slightly adjusted

**Pull request closed without merging**
