### PR TITLE
Adjust coding style in "bin" scripts

### PR DESCRIPTION
**Pull request by Josef-Friedrich**
The main shell script (start-mailserver.sh) uses two spaces for
indentation. All other shell scripts should use this coding
style.

### CODE REVIEW

**Comment by tomav** [comment]
Seems to have a conflict here. Could you resolve it?
Thanks for you work @Josef-Friedrich

**Comment by Josef-Friedrich** [comment]
The pull request should be now mergeable

**Comment by tomav** [comment]
Thanks!

**Comment by tomav** [comment]
@Josef-Friedrich Travis Build disapeared here, and now master is broken after this merge.
Could you have a look please?
https://travis-ci.org/tomav/docker-mailserver

Thanks.

**Comment by mathuin** [comment]
A "fi" seems to have been left out in addmailuser, before the 'else // usage'.

**Comment by Josef-Friedrich** [comment]
I’m sorry. A create soon a new pull request

**Comment by Josef-Friedrich** [comment]
#286 should fix the build process

**Pull request merged**
