### PR TITLE
F2B script unusable - fixes #1677

### LINKED ISSUE #1677: fail2ban script output incorrect
## Context
I noticed today, that the output from the fail2ban script is a bit weired:

    root@mail:/# fail2ban
    iptables: No chain/target/match by that name.
    iptables: No chain/target/match by that name.
    Banned in postfix-sasl:
    Banned in postfix-sasl:
    Banned in postfix-sasl: 58.57.4.238
    Banned in postfix-sasl:
    iptables: No chain/target/match by that name.
    Banned in sshd:
    Banned in sshd:
    Banned in sshd: 58.57.4.238
    Banned in sshd:

My iptables at the time:

    root@mail:/# iptables -L -n
    Chain INPUT (policy ACCEPT)
    target     prot opt source               destination
    f2b-postfix-sasl  tcp  --  0.0.0.0/0            0.0.0.0/0
    
    Chain FORWARD (policy ACCEPT)
    target     prot opt source               destination
    
    Chain OUTPUT (policy ACCEPT)
    target     prot opt source               destination
    
    Chain f2b-postfix-sasl (1 references)
    target     prot opt source               destination
    DROP       all  --  58.57.4.238          0.0.0.0/0
    RETURN     all  --  0.0.0.0/0            0.0.0.0/0

As you can see, only one IP is blocked in the f2b-postfix-sasl chain.
However the script reports a lot of empty lines "Banned in " + also falsely reports the IP banned in the sshd chain.

I copied over the [version before](https://github.com/tomav/docker-mailserver/blob/b08c9b42ed2a211784499a3adbc46d4a80ad4b71/target/bin/fail2ban) the refactoring #1654, which outputs correctly:

    root@mail:/# bash fail2ban.old
    iptables: No chain/target/match by that name.
    iptables: No chain/target/match by that name.
    Banned in postfix-sasl: 58.57.4.238
    iptables: No chain/target/match by that name.

### *What* is affected by this bug?
/usr/local/bin/fail2ban

### *When* does this occur?
always

## Actual Behavior
Incorrect output

## Expected behavior (i.e. solution)

Same output as before the refactoring.

## Solution
None yet. I will take a closer look by the end of the week. @aendeavor do you have an idea what could be the cause?

### PR DESCRIPTION
**Pull request by aendeavor**
This PR closes #1677

**Notice**: I changed the `test/mail_fail2ban.bats` file **back** to its original state with very very minor adjustments (inserting a comma, adding a whitespace, etc.).

### CODE REVIEW

**Comment by aendeavor** [comment]
@casperklein I even improved on the old version by not printing the useless `iptables: No chain/target/match by that name.` line

**Comment by aendeavor** [comment]
@casperklein I would merge this with the debug trace in it and push another commit on master since I changed up some other things unrelated to this PR as well.

**Comment by casperklein** [comment]
> @casperklein I even improved on the old version by not printing the useless `iptables: No chain/target/match by that name.` line

Nice! I didn't use the "fail2ban" script directly, but with [mailctl](https://github.com/casperklein/docker-mailserver-mailctl) where I also [filtered](https://github.com/casperklein/docker-mailserver-mailctl/blob/19a9b86d68863682485b6234a10ec308ab494f0d/mailctl#L77) that out. If your solution works, I can remove that 😃  I will take a look tonight.

**Comment by casperklein** [comment]
@aendeavor I can confirm, it works like a charm. Thank you!

**Comment by aendeavor** [comment]
I'm glad it works!

**Pull request merged**
