### PR TITLE
Mention submodule dependency

### PR DESCRIPTION
**Pull request by arneke**
Mention that you have to manually initialize and update submodules, otherwise you find out after a very long wait.

### CODE REVIEW

**Comment by kiliant** [comment]
👍 haha had to find that out myself.

ci should be just fine, i had those "hickups" as well. maybe @tomav can restart it

**Comment by arneke** [comment]
Actually, I had intermittent issues with that PGP key as well, the one that killed the build, as well as multiple failures in a row with db.local.clamav.net (round robin DNS afaik). So I have been trying to get clean build for two days now.

Pretty sure it's not an issue with the server I am building this on, it's a bit dated, but on a solid connection. Making the build more resilient, or making a base image to build on top of, may qualify for a separate ticket. But I haven't looked into what you have discussed previously.

**Comment by tomav** [comment]
Restarted

**Comment by tomav** [comment]
Thanks

**Pull request merged**
