### PR TITLE
WIP: Modularize tests

### PR DESCRIPTION
**Pull request by martin-schulze-vireso**

### CODE REVIEW

**Comment by erik-wramner** [comment]
You seem to have done quite a lot. How about trying to close this PR when the tests are green again and proceed with a new one? That way we can get the improvements in and avoid a tricky merge later in case there are changes.

**Comment by martin-schulze-vireso** [comment]
@erik-wramner you're right, I planned on rebasing on master and then going on, but further work will land just as well on a new PR. I'm still trying to reproduce the test failure locally because I don't want to feedbackloop via CI.

**Comment by erik-wramner** [comment]
Tests are green, let us know when you want to merge.

**Comment by martin-schulze-vireso** [comment]
Go on and merge if the changes look good to you. I don't have any pending local changes.

**Pull request merged**
