### PR TITLE
Default imap folders

### PR DESCRIPTION
**Pull request by millaguie**
Create default imap folders for Trash, Drafts and Sent.

### CODE REVIEW

**Comment by citec** [comment]
Hi, nice feature. As this will be used by multilanguaje users, or even someone who wants different default imap folders, maybe would be good to have the option to set an ENV var with an array of folders to be created, then, if set, create those on the start-mailserver.sh script.

**Comment by millaguie** [comment]
Hi,

I'm spanish speaker, all my setup is in spanish and it works like a charm. But...  probably some one would like to use another scheme... let me think about your workaround...

Thanks,

**Comment by tomav** [comment]
Hi @millaguie, nice PR thanks. I'll merge it once you've fixed the tests:

    test #18 "docker exec mail ls -A /var/mail/localhost.localdomain/user1" failed:
      expected "cur\nnew\ntmp"
      got ".Drafts\n.Sent\n.Trash\ncourierimapsubscribed\ncur\nnew\ntmp"
    test #19 "docker exec mail ls -A /var/mail/otherdomain.tld/user2" failed:
      expected "cur\nnew\ntmp"
      got ".Drafts\n.Sent\n.Trash\ncourierimapsubscribed\ncur\nnew\ntmp"

About @citec improvement, it's another feature.

**Comment by citec** [comment]
I am spanish too, but think about someone wanting to have the Archive folders pre-created, or the Templates one, etc.

**Comment by millaguie** [comment]
Sorry about the tests, I noticed too late.

**Comment by tomav** [comment]
No problem @millaguie, Travis is here ;-)
Thanks for your PR.

**Pull request merged**
