### PR TITLE
Allow regex aliases

### PR DESCRIPTION
**Pull request by shimunn**
Since it like to use a unique email address for each service I use and I've got tiered on creating a new account each time I thought it would be a good idea to support regex aliases via postfix.

### CODE REVIEW

**Comment by johansmitsnl** [comment]
Many tests fail now specific to email delivery. Could you verify/fix this?

**Comment by shimunn** [comment]
I don't think that's caused by my modifications, tests for master and stable branches are failing as well.

**Comment by johansmitsnl** [comment]
Restarted the build

**Comment by erik-wramner** [comment]
Nothing has happened since November 2018. If this is still relevant, please rebase from the current master where the tests are green to see if that helps. If there is no activity for two weeks I think we should close this PR.

**Comment by erik-wramner** [comment]
Closing for inactivity.

**Pull request closed without merging**
