### PR TITLE
WIP: fix linting errors reported by hadolint

### PR DESCRIPTION
**Pull request by fbartels**
Hadolint is a nice too to detect common pitfalls in Dockerfiles. If desired I can add it to the travis file as well.

### CODE REVIEW

**Comment by tomav** [comment]
I restarted the build multiple times but there are always 1 or 2 tests `not ok`.
Can you have a look?

**Comment by tomav** [comment]
Sorry, have not seen it's still a WIP.

**Comment by fbartels** [comment]
With the last commit the tests should be green now.  Apart from fixing hadolint warnings (and ignoring some others) I have added some todos to the code for items that should be refactored/changed. 

I would suggest to squash before merge. If you want I could also split todos from the linting.

**Comment by fbartels** [comment]
hm.. now there are test failures around opendkim. I am going to split my changes into multiple prs and am going to create issues for my todos.

**Comment by fbartels** [comment]
Closing here since I already created the followup prs.

**Pull request closed without merging**
