### PR TITLE
Provide version information through labels

### PR DESCRIPTION
**Pull request by fbartels**
Can be retrieved by calling e.g. `docker inspect tvial/docker-mailserver:testing`

Sample output:

```
$ docker inspect -f '{{ range $k, $v := .ContainerConfig.Labels -}}
> {{ $k }}={{ $v }}
> {{ end -}}' tvial/docker-mailserver:testing
maintainer=Thomas VIAL
org.label-schema.description=A fullstack but simple mailserver (smtp, imap, antispam, antivirus, ssl...)
org.label-schema.name=docker-mailserver
org.label-schema.schema-version=1.0
org.label-schema.url=https://github.com/tomav/docker-mailserver
org.label-schema.vcs-ref=7580aec
org.label-schema.vcs-url=https://github.com/tomav/docker-mailserver
org.label-schema.version=v6.1.0-111-g7580aec
```

### CODE REVIEW

**Comment by erik-wramner** [comment]
Looks good but I have one question. If the docker images are built from docker hub and not from Travis then they will just run the Dockerfile and ignore our Makefile. In that case your changes will do nothing except when we build manually.

**Comment by fbartels** [comment]
Ah, yes indeed. At this point in time the build args would not be passed and the values would be empty in the resulting image.

It seems this can be mitigated through build hooks (https://docs.docker.com/docker-hub/builds/advanced/). Currently have a test build running. Will push the required hook if my change succeeds.

**Comment by erik-wramner** [comment]
No rush or anything, I just want to check that you are not waiting for me on this and/or your other PRs?

**Comment by fbartels** [comment]
It seems we both forgot about this. Let me rebase, wondering about some of the Makefile changes, though.

**Comment by erik-wramner** [comment]
Right. If you are waiting for me on something, please just leave a comment.

**Comment by fbartels** [comment]
@erik-wramner is `not ok 198 checking setup.sh: setup.sh email add and login` a known failure?

**Comment by erik-wramner** [comment]
Yes, it happens every now and then.

**Comment by fbartels** [comment]
OK, after regriggering tests ar green. Let's merge.

**Pull request merged**
