### PR TITLE
Miscellaneous cleanup / housekeeping

### PR DESCRIPTION
**Pull request by aendeavor**
This PR is just housekeeping and cleanup here and there, nothing in particular, but it bugged me to see these small areas where I could improve on.

### CODE REVIEW

**Comment by casperklein** [comment]
One question regarding: https://github.com/tomav/docker-mailserver/pull/1641/commits/060e2c5427ae3e640bf03a7a18c99a15bb0518c5

>: >/etc/postfix/vmailbox

I normaly use `> /foo/bar` to create an empty file. What is the colon for in this case?

**Comment by aendeavor** [comment]
> One question regarding: [060e2c5](https://github.com/tomav/docker-mailserver/commit/060e2c5427ae3e640bf03a7a18c99a15bb0518c5)
> 
> > : >/etc/postfix/vmailbox
> 
> I normaly use `> /foo/bar` to create an empty file. What is the colon for in this case?

Using `> /foo/bar` is actually fine because it's clear that you're redirecting an empty `stdout` in that file essentially creating an empty one. But it is good style in idiomatic Bash seeing a command before the redirection. The colon (and in this case `true` as well) would serve this no-op function:

noop

However this will not actually affect the outcome.

**Comment by casperklein** [comment]
Ok, thank you for clarification.

**Comment by aendeavor** [comment]
No problem:)

**Pull request merged**
