### PR TITLE
Issue 538

### PR DESCRIPTION
**Pull request by kiliant**
Extended setup.sh to be able to handle alias management.

Aliases are configured via _postfix-virtual.cf_.

Implementation has been manually tested, I may add integration tests later on.

### CODE REVIEW

**Comment by kiliant** [comment]
Does anyone know a nice way of reloading postfix's config (e.g. the aliases) without restarting the whole container?
I tried to restart/reload it (using postmap on /etc/postfix/virtual breaks it).
It would be nice, if we could extend the scripts to automatically apply the new configurations itself..

**Comment by tomav** [comment]
Hi @kiliant, if the domain is already in postfix configuration, just updating alias file and `postfix reload` is enough.
If the domain is new, `start-mailserver.sh` does more.

**Comment by kiliant** [comment]
Thanks for your tip, I will have a look into that!

By the way, could you confirm why the test fails? I did not even change something that could lead to a failure -> _"not ok 125 checking dovecot: only A grade TLS ciphers are used"_

**Comment by tomav** [comment]
```
not ok 125 checking dovecot: only A grade TLS ciphers are used
# (from function `assert_success' in file test/test_helper/bats-assert/src/assert.bash, line 114,
#  in test file test/tests.bats, line 1041)
#   `assert_success' failed
# 
# -- command failed --
# status : 1
# output (16 lines):
#   Unable to find image 'instrumentisto/nmap:latest' locally
#   latest: Pulling from instrumentisto/nmap
#   627beaf3eaaf: Pulling fs layer
#   9a1084c43a8f: Pulling fs layer
#   6e5c0f8927db: Pulling fs layer
#   627beaf3eaaf: Verifying Checksum
#   627beaf3eaaf: Download complete
#   9a1084c43a8f: Verifying Checksum
#   9a1084c43a8f: Download complete
#   627beaf3eaaf: Pull complete
#   9a1084c43a8f: Pull complete
#   6e5c0f8927db: Verifying Checksum
#   6e5c0f8927db: Download complete
#   6e5c0f8927db: Pull complete
#   Digest: sha256:61a069f79e94a4645b476c29aed61d9981d7a62538b66f3664eac9358aee45de
#   Status: Downloaded newer image for instrumentisto/nmap:latest
# --
# 
```

The ouput is the external image load.

**Comment by tomav** [comment]
@kiliant could you add integration tests on that part?

**Comment by kiliant** [comment]
Sorry, I am quite busy at the moment.

Could you assist me with adding integration tests?
What should I test for? That the file is created correctly by the different commands (according to postfix syntax) or that test mails to aliases are correctly delivered?

Thanks!

**Comment by tomav** [comment]
Hi @kiliant, testing that the alias is created correctly is a good start.
Look at the tests folder, there's a tests.bats, it's pretty straight forward.

**Comment by kiliant** [comment]
ok, I am somehow unable to successfully check for the desired output.

**Comment by kiliant** [comment]
Do you know why there is a timeout? The tests run locally just fine..

**Comment by tomav** [comment]
`run` command is used to match an assertion and you sometimes use it 3 times. I think only the latest will be used. I can't look deeply now sorry

**Comment by kiliant** [comment]
Well, the build/test system seems to be somewhat buggy at the moment, now the build process itself failed.

**Comment by kiliant** [comment]
Ok, looks good now imho.

**Comment by tomav** [comment]
Thanks.

**Pull request merged**
