### PR TITLE
selective service disable

### PR DESCRIPTION
**Pull request by KyleOndy**
This pull request is in response to #216.

This PR only selectively disabled either clamav, spamassassin, or amavis.

I am not sure if the config files needs to be touched at all.

### CODE REVIEW

**Comment by KyleOndy** [comment]
Build timed out. It built on my [branch of travis](https://travis-ci.org/KyleOndy/docker-mailserver/builds/149836649).

**Comment by tomav** [comment]
Restarted.

**Comment by tomav** [comment]
Thank you!

**Comment by ep0ch2** [comment]
Many thanks for this, the following settings work:
    - DISABLE_AMAVIS=0
    - DISABLE_SPAMASSASSIN=1
    - DISABLE_CLAMAV=1

however with disable_amavis=1 i can't send/receive emails. so perhaps some extra config changes are needed,

**Comment by KyleOndy** [comment]
Looking into it now.

**Comment by tomav** [comment]
The answer is probably [here](https://github.com/tomav/docker-mailserver/blob/master/target/postfix/main.cf#L71) and perhaps [here](https://github.com/tomav/docker-mailserver/blob/master/target/postfix/master.cf#L84)

**Comment by tomav** [comment]
Perhaps, to simplify, a `DISABLE_FILTERS` should be easier to implement (no matrix with the 3 current vars, but of course, they bring more granularity).

Let me know.

**Pull request merged**
