### PR TITLE
Accounts and virtual conf split

### PR DESCRIPTION
**Pull request by dy0nysos**
#10 Separate virtuals and accounts.

### CODE REVIEW

**Comment by tomav** [comment]
Good job @dy0nysos!
But I'm thinking that `aliases` and `redirects` are 2 different things (and we need both).

`user@domain.tld|otheruser@domain.tld,otheruser@otherdomain.tld` is nice but with this, we have to manage 1 entry per alias, no?
I mean 1 real account, with 50 aliases will have 1 entry or 50 entries?

**Comment by dy0nysos** [comment]
Sorry I thought I answered your question.

Here I'm managing redirects only. user@domain.tld to otheruser@domain.tld,anotherone@domain.tld etc.

In facts, if you need one mail to have several aliases, you'll have one line per alias.

Can you see a ( new ? ) file structure that will allows us to have several aliases for one email on a single line ?

Maybe could we add another conf file, `aliases.cf` with that kind of structure : 
`mailtobealiased|alias1,alias2,alias3` or something of this kind ?

**Comment by tomav** [comment]
Yes, this kind of format existed before the PR, aliases were managed, not redirects.

The point is that `accounts.cf` remains mandatory and must be parsed when the container starts because there are commands to execute to create these accounts.

We can add a new file format and parse it, but I think it's not really necessary.
Aliases and redirects may be static files in postfix format, just copied from `/tmp`to `/etc/postfix/virtual`.

Aliases and redirects are managed the same way.
http://www.postfix.org/VIRTUAL_README.html#forwarding

Sorry, I'm on vacation and can't do more than answering at this time.
I'll be back on monday.

**Comment by dy0nysos** [comment]
Okay, I'll change my code to change the behavior according to your proposition.

Enjoy your vacation ! :+1:

**Comment by tomav** [comment]
Thank you.

**Comment by tomav** [comment]
I don't know why `build` fails on the docker registry. I'm re-trying locally.

**Comment by tomav** [comment]
I'm not blind, it works locally. Waiting for the registry.

**Comment by tomav** [comment]
Latest docker registry build is `done`.
https://hub.docker.com/r/tvial/docker-mailserver/builds/bjkcm6jaq4bzfaizu5mqhrp/

**Comment by dy0nysos** [comment]
Nice !

**Pull request merged**
