### PR TITLE
Getting rid of ELK & Update Compose

### PR DESCRIPTION
**Pull request by aendeavor**
This PR starts the process of removing ELK from the current builds.

## What has already been done?

- [x] The ELK directory has been removed
- [x] Removed ` docker-compose.elk.yml.dist`
- [x] Removed ` docker-compose.filebeat.yml.dist`
- [x] Updated Docker Compose files

## What needs to be done?

- [x] The elk build on Docker Hub will be removed by @tomav  

## Rationale

For ELK, it's clear. Filebeat was removed with release 7, so removed this compose file too.

Docker Compose is currently on stable version `1.26.2` which translates to compose file version `3.8`. I updated to `3.7` and formatted the YAML files properly.

### CODE REVIEW

**Comment by tomav** [comment]
Hi @aendeavor I can remove it from Docker Hub when new version will be merged/released.

**Comment by aendeavor** [comment]
Alright @tomav 👍🏼

FYI: This PR is ready for merging. I'll merge it in a few minutes, so you can proceed with removing the build from Docker Hub.

**Comment by tomav** [comment]
ELK build dropped on Docker Hub.

**Comment by aendeavor** [comment]
I posted this in #1207 too, in case you wonder. Is there any way the `/elk` build in `ci/dockercloud/ is still active?

image

**Pull request merged**
