### PR TITLE
activate SA shortcircuit features via env, fixes #1118

### LINKED ISSUE #1118: Allow to use Spamassassin's shortcircuit bayes_99 and bayes_00 feature
Spamassassin allows administrators to give their Bayes databases greater emphasis by short circuiting the analytical process. 

This is normally configured in /etc/spamassassin/local.cf at the very end. However, it is rather annoying, to edit this file with every update of the container.

Having two environment variables to configure this would be very helpful.

Proposal: 

- ```SA_SHORTCIRCUIT_BAYES_SPAM``` - if set to 1, then it will activate ```shortcircuit bayes_99 spam```
- ```SA_SHORTCIRCUIT_BAYES_HAM```- if set to 1, then it will activate ```shortcircuit bayes_00 ham```

### PR DESCRIPTION
**Pull request by phish108**

### CODE REVIEW

**Comment by phish108** [comment]
@tomav Not sure why this PR fails. It seem that you are not considering it. 

Please tell me what to do, to include this feature. 

Thanks

**Comment by erik-wramner** [comment]
I think this looks fine. Please rebase from the current master to see if the tests succeed, the failure was probably not caused by your changes. It would be nice with a test though. Perhaps you can use two of the existing docker images, one with the options set and one without them. Then you can add a test case that verifies the configuration files to make sure that they have been updated (or not) as expected in `test/tests.bats`.

**Comment by erik-wramner** [comment]
@phish108 this has been waiting for action since August. Unless you get back to me fairly soon I'll close it.

**Comment by erik-wramner** [comment]
A pity, but as nothing has happened I'll close this.

**Comment by phish108** [comment]
Did not have time to look at it and I did not get the notification through. Please reopen.

**Comment by erik-wramner** [comment]
Of course, I'll reopen it.

**Comment by phish108** [comment]
@erik-wramner rebased to the current master and updated my PR. No merge conflicts on my side and travis does not complain either.

**Comment by erik-wramner** [comment]
Ough, suddenly there are 101 changed files and 189 commits! That won't work. We need to get rid of that and just get your changes in. You must have done a merge somewhere.

Perhaps the easiest way is to just create a new branch from master, apply the real changes manually and make a PR from that? As far as I recall there were not that many changed files after all. Alternatively use git magic to go back in time, rebase and apply the real changes as one or more small commits.

**Comment by phish108** [comment]
OK, the changes are only due to the git rebase. I just have the branch, but I can create a new branch and cherry pick my changes. This takes a few days.

**Comment by erik-wramner** [comment]
No problem.

**Comment by phish108** [comment]
I close this in favour of #1372

**Pull request closed without merging**
