### PR TITLE
postscreen implementation altered

### PR DESCRIPTION
**Pull request by 17Halbe**
made the config files `postfix-sender-access.cf` as well as `postfix-receive-access.cf` optional.

main.cf modification happens when either the user uses the setup.sh script or when providing a ...-access.cf file.

Please have a look if the postfix restart is implemented correctly. (I wasn't sure if `service postfix reload`, `supervisorctl restart postfix` or `/etc/init.d/postfix restart` is desired) (`service postfix reload` gets trapped anyway.)
This will most probably solve #844

### CODE REVIEW

**Comment by 17Halbe** [comment]
Ah forgot to mention that the tests succeed on my machine.

**Comment by 17Halbe** [comment]
Tests still passing on my side..

**Comment by johansmitsnl** [comment]
Could you fix the conflict so that I can merge it?

**Comment by 17Halbe** [comment]
See https://github.com/tomav/docker-mailserver/pull/846#issuecomment-366501435
;)

**Comment by 17Halbe** [comment]
Should have closed #847 and #844

**Pull request merged**
