### PR TITLE
Upgrade to ubuntu:16.04

### LINKED ISSUE #500: opendmarc crashes when no From field is specified
Got bitten by this bug when testing the server using telnet.

See https://bugs.launchpad.net/ubuntu/+source/opendmarc/+bug/1574562
I fixed this on my (stripped down) version by using ubuntu 16.04 LTS which has newer opendmarc.

### PR DESCRIPTION
**Pull request by 42wim**
Upgrade to ubuntu:16.04. 
Fixes #500 
All tests are passing.

### CODE REVIEW

**Comment by tomav** [comment]
Hi @42wim, thanks for that!
1 test is failing, just restarted travis to confirm 👍 
```
not ok 6 checking configuration: hostname/domainname override: check headers of received mail
# (from function `assert_success' in file test/test_helper/bats-assert/src/assert.bash, line 114,
#  in test file test/tests.bats, line 46)
#   `assert_success' failed
# 
# -- command failed --
# status : 1
# output : 
# --
# 
```

**Comment by tomav** [comment]
More errors on second run : https://travis-ci.org/tomav/docker-mailserver/builds/205292420

**Comment by 42wim** [comment]
I can't reproduce this, tried 2 times with clean build and I'm getting ```127 tests, 0 failures```

**Comment by JCBird1012** [comment]
I've successfully gotten a version of this image running on Ubuntu 16.04. I know for certain that Dovecot, Postfix, and Fail2Ban work, but I can't be sure about the things I don't use (such as ClamAV and Spamassassin), however from the looks of it, they should work just fine. 

If you'd like, I can submit a PR with my changes and see if it passes all tests on Travis. Let me know!

**Comment by tomav** [comment]
Tests 6 still fails. https://travis-ci.org/tomav/docker-mailserver/builds/205292420

**Comment by tomav** [comment]
Now in #571

**Pull request closed without merging**
