### PR TITLE
Add ldap auth for postfix and dovecot

### PR DESCRIPTION
**Pull request by dennis95stumm**

### CODE REVIEW

**Comment by tomav** [comment]
Hi @dennis95stumm, what do we do with #335 ?

**Comment by dennis95stumm** [comment]
My opinion is that there are tests missing. @alinmear could rebase on develop after merging this pull request and add a pull request for kopano support. But lets ask also @alinmear.

**Comment by alinmear** [comment]
Hey @dennis95stumm sounds good. i will rebase and make a new pull request as proposed!

**Comment by dennis95stumm** [comment]
The build hung up at the update of clam av. But in the forked repository the tests passed.

**Comment by tomav** [comment]
Waiting for @alinmear to respond on #335. Otherwise this PR is ready to merge.

**Comment by alinmear** [comment]
@tomav @dennis95stumm picked up my changes and extended them, also with several integration tests. I will rebase on this and make a pull request for kopano support. This PR will be a small one, compared to this one, because it is all about changing the virtual_transport parameter for the mda side. Kopano uses ldap in the background (openldap or ad) and this can basically covered with this PR.

After merging this pull request i will rebase and make a new pull request. So you could just close #335.

**Comment by tomav** [comment]
Roger That.

**Pull request merged**
